# 空转（Visium）CNV 臂 —— 预注册（2026-09-24，**执行前**登记）

> 法则 3.1：参数必须显式常量化并登记。法则 3.2：阈值一经确定不得事后调整。
> 本文件在**首跑之前**写成。下面的输入定义、守卫与判读此后不得改动；
> 要改必须另开一版，写明改了什么、为什么、改之前跑出了什么。

---

## 0. 本臂是什么，不是什么

**是什么**：在 **Visium spot** 上调用拷贝数变异，据此判定**逐 spot 的恶性 / 非恶性**。
这是全项目**唯一**的恶性判定来源。

**不是什么**：

- **不是**单细胞 CNV 的重跑。单细胞 CNV 已由用户 2026-09-24 判定**失败**并整体退出
  （历史见 `results/03_cnv/ANCHOR_PREREG.md`、`SCEVAN_PREREG.md` 顶部横幅）。
- **不是** RCTD 的产物。RCTD 只做**构成估计与纯度 QC**，**不判恶性**。
  这是源论文自己的分工（Peng 2026 Cancer Cell 方法段：恶性由 SpatialInferCNV 判，
  RCTD 用于纯度 QC），也是用户 2026-09-24 的裁定。
- **不是**"把单细胞 CNV 结论搬到空间上"。两者不共享细胞、不共享坐标。

### 0.1 从单细胞 CNV 的失败里必须继承的两条教训

| 教训 | 具体表现（已发生的事） | 本臂的对应设计 |
| :--- | :--- | :--- |
| **锚不稳 ⇒ 全盘作废** | 同一批 3,890 正常细胞，三次跑出 **0% / 13.6% / 49.8%**；`norm.cell.names` 只算基线不参与判决；99 次里 30 次不可用 | **§4 门 SC2（锚可复算）是本臂的第一道硬门**，先于任何结论 |
| **"没跑" ≠ "没失败"** | SCEVAN 第二臂一例未跑，却差点被读成"未被证伪" | §5.3 明写：未运行的臂在本臂报告里记 **NOT RUN**，不得记作阴性 |

---

## 1. 要回答的唯一问题

> **在本队列的 Visium spot 上，能否给出一份逐 spot 的恶性判定，且该判定可复算、有可证伪的阴性对照？**

**不**回答：亚克隆结构、系统发育树、克隆与分期的关系、预后。
这些是原文的后续目标，本臂不碰（见 §6）。

---

## 2. 输入定义（逐字）

### 2.1 表达矩阵

- 来源：`data/visium_spatial/<GSM>_<P>_<期>/filtered_feature_bc_matrix/`
- **只取 `Gene Expression` 行**，剔掉 `Antibody Capture` 行
  （其计数量级可达 1e6，混入会毁掉 CNV 基线 —— 见 `SPATIAL_QC_PREREG.md` §1.1）
  > 🔴 **2026-09-29 登记更正：抗体行数不是恒定的 35。**
  > 逐张 dump 56 张 `features.tsv.gz` 的 type 列实测：**45/56 张有 35 行 `Antibody Capture`**
  > （共 18,120 行），**11/56 张为 0 行**（共 18,085 行）；**`Gene Expression` 行数恒为 18,085**。
  > P4 自己四张就是混合的：Normal 35 / AAH 0 / AAH-1 35 / LUAD 0。
  > 原文「35 行」的写法只在 45/56 张上成立。
  > **影响面**：SC0② 原先按「抗体行 == 35」判 ⇒ 对 11 张会**假报警**（首跑即栽在这）。
  > 改为 **`抗体行 ∈ {0, 35}` 且逐张上报**；`Gene Expression == 18,085` 的判据不变。
  > 本更正**不改变**剔除动作本身（抗体行一律剔），只更正「有多少行要剔」的期望值。
- 组织内 spot 集合 = `SPATIAL_QC_PREREG.md` 冻结的 `spot_mask.tsv.gz`
  （✅ **2026-09-25 已签字并冻结落盘**，见该文件 §3 / §3.3）
- 🔴 实际落地路径：`results/08_spatial_deconv/spot_mask.tsv.gz`（RCTD 56 张即用它，见 `RCTD_PREREG.md` §13.6）
- 合并方式：**按患者合并其全部切片**（原文按 patient 建克隆与树）

### 2.2 上皮 spot 子集 —— ✅ **已裁定（2026-09-25 晚）**

> 🔴 **生效口径见 §11 —— 但 §11 第 3 项（权重阈值）已被 §12.1 改签为 `argmax == 上皮`；
> 以 §12.1 为准。** 本节文字**保留不删**（改之前的状态也是记录）。

原文只在**上皮 spot** 上跑 SpatialInferCNV。我们的上皮 spot 由 **RCTD 权重**给出
（`RCTD_PREREG.md`；病理线不得供标签，见 `SPATIAL_QC_PREREG.md` §5.3）。

**待签字项**：① 用粗版还是细版 RCTD 参考；② 上皮类目的清单；③ 权重阈值取多少；
④ 阈值未达的 spot 是剔除还是单列一档。

⚠️ **不得**在看过 CNV 结果之后再回来调这个阈值（法则 3.2）。

### 2.3 基因序（**已就绪，可复用**）

- `results/03_cnv/infercnv_smoke/gene_order_hg38.tsv`
- 来源：GENCODE **v44 (hg38)** GTF ＋ HGNC `complete_set`，经 `prev_symbol`/`alias_symbol` 解析改名
- 实测匹配率 **99.62%**（18,069 个基因里 18,000 匹配，69 未匹配）
- sha256 `1f88af4ef06710a0e60632406c7a5db8f440b1764a55e191f31c3a5c8b097194`
- ⚠️ 该文件是为 **snRNA** 建的，空转的基因名需**重新过一遍同一脚本**并**重算哈希**，
  不得直接沿用旧哈希（空转 features 里的 `HSPA14` / `TBCE` / `TMSB15B` 是**双探针**，需按 symbol 求和后取一次）

---

## 3. 方法：用 `infercnv` 实现原文记录的 SpatialInferCNV 流程

### 3.1 为什么不用 SpatialInferCNV 本体

原文用的 `SpatialInferCNV`（<https://github.com/aerickso/SpatialInferCNV>）
**仓库里没有许可证**（LICENSE 文件是模板占位符 "What license is it under?"）。
⇒ 我们**不引入**它，改为**按原文方法段逐字实现同一套流程**，跑在
`infercnv` 之上（Bioconductor，**BSD_3_clause**，许可明确）。

⚠️ **由此产生的一条登记**：本臂产出的应描述为
「**原文方法的复现**」，**不是**「原文代码的运行」。报告里不得写"用了 SpatialInferCNV"。

### 3.2 环境（**已实测可用，2026-09-24**）

```bash
export LD_LIBRARY_PATH=/home/eto/local/jags/lib:$LD_LIBRARY_PATH
R_LIBS=/home/eto/Rlibs/infercnv:/home/eto/R/x86_64-pc-linux-gnu-library/4.2:/usr/local/lib/R/site-library:/usr/lib/R/site-library
```

| 件 | 位置 / 版本 | 实测 |
| :--- | :--- | :--- |
| JAGS | `/home/eto/local/jags/bin/jags`，**4.3.2** | ✅ 自建，无需 root |
| `rjags` | `/home/eto/Rlibs/infercnv/rjags` | ✅ 装载通过（需上面的 `LD_LIBRARY_PATH`） |
| `infercnv` | `/home/eto/Rlibs/infercnv/infercnv`，**1.23.0** | ✅ 装载通过 |
| `coda` / `RColorBrewer` | `/usr/local/lib/R/site-library` | ✅ |

⚠️ **旧记录更正**：本项目先前多处记着「infercnv 卡在 rjags ⇒ 需系统 JAGS（未装）」。
**该记录已过期。** JAGS 早已自建安装且可用 ⇒ 原文的 `HMM=TRUE` **是够得着的**
（既有的 P4 冒烟之所以没跑 HMM，是因为那份预注册当时把 `P_HMM` 设成了 `FALSE`，
不是因为环境不允许）。

### 3.3 参数 —— **逐字照抄原文，一个都不改**

原文方法段（PMC12980502，Methods「Spatial infer-CNV」）：

> ...by applying the following parameters: `cutoff = 0.1`, `cluster_by_groups = TRUE`,
> `HMM = TRUE`, and `denoise = TRUE`.

```r
# 08_spatial_deconv/<NN>_run_spatial_cnv.R
P_CUTOFF            <- 0.1     # 原文
P_CLUSTER_BY_GROUPS <- TRUE    # 原文
P_HMM               <- TRUE    # 原文 —— 本机可用（§3.2）
P_DENOISE           <- TRUE    # 原文
P_REF_GROUP         <- "多锚并列：C 主 + D 对照"   # ✅ 2026-09-25 晚签字，见 §11 第 5 项 / §11.2
P_THREADS           <- 3       # 本机 load average 长期 57–70，不拉高
```

⚠️ 与既有 P4 冒烟**不同**：那份跑的是 `P_HMM=FALSE`、`analysis_mode="subclusters"`、
参考为「同患者 Normal 全部上皮」。**本臂不继承那些取值**，按原文重设。

### 3.4 🔴 **锚（参考 spot）—— 本臂最大的缺口，必须签字**

> ✅ **已裁定（2026-09-25 晚）：多锚并列（C 主 ＋ D 对照），报逐 spot 判定一致率。
> A、B 本次 NOT RUN。生效口径见 §11.2。** 本节文字保留不删。

原文选参考 spot 的**三步法**（逐字）：

> the '**without reference**' mode was first used to classify spots into different clones
> based on clustering patterns. Second, the inferred clone information for each spot was then
> mapped onto the UMAP embedding. Third, spots exhibiting the **lowest CNA signal or variation**,
> which mapped precisely to the annotated "**normal lung epithelial**" population, were selected
> as reference spots for the final round of SpatialInferCNV analysis. If no such cluster was
> identified, steps 1–3 were repeated with **finer clone clustering** until a pure normal lung
> epithelial cluster was selected.

**问题**：第三步把「最低 CNA」和「病理学家标注的正常肺上皮」**两个条件一起**要求。
前者我们能算，**后者我们没有**——病理线已判死，不得供标签（`SPATIAL_QC_PREREG.md` §5.3）。

原文另有一条**兜底**：12 例（P1,P2,P3,P4,P6,P9,P14,P15,P17,P20,P21,P24）直接用
**全部**「正常肺上皮」标注 spot 作参考 —— 这条同样依赖病理标注，我们也用不了。

#### 三个候选处置（**待用户签字，未定之前不得开跑**）

| # | 方案 | 依据 | 风险 |
| :---: | :--- | :--- | :--- |
| **A** | **纯无参**：`without reference` 模式跑完，**自动取 CNA 信号最低的克隆**作参考 | 原文第 1、3 步的前半句；**不需要任何标签** | 🔴 **循环论证风险**：无参模式下基线是**全体 spot 的均值**，若切片以肿瘤为主，最低 CNA 的克隆**可能仍是肿瘤**。单细胞臂就是这么塌的 |
| **B** | **用 RCTD 复核锚**：先按 A 取候选锚，再用 RCTD 权重检查该克隆是否由**正常上皮类**（AT2/AT1）主导；不主导则按原文"更细分克隆"重来 | 原文第三步的**意图**（要求锚是正常上皮）用**另一个模态**实现；且 RCTD 的角色仍只是**纯度 QC**，不判恶性 —— 与用户裁定一致 | 需要把 `SPATIAL_QC_PREREG.md` §5.4「CNV ↔ RCTD 无共享对象」**修订为**「共享**锚校验**这一件事，仍禁止恶性×权重的乘法」。**这是一处口径修改，必须单独签字** |
| **C** | **同患者 Normal 切片作锚**：有 Normal 切片的患者直接用其 Normal 切片的上皮 spot 作参考 | 我们队列里确有 Normal/AAH 切片；这是"同患者正常组织"的**直接**测量，不需要标签 | ⚠️ 只有部分患者有 Normal 切片（多数只有 AAH/AIS/MIA/LUAD）；**覆盖不全 ⇒ 患者间锚定义不一致**，正是单细胞锚定臂出问题的地方 |

🔴 **建议 A＋B 组合**（B 作为 A 的守卫），但**这是建议不是裁定**。
**三个方案未签字之前，本臂不跑。**

---

## 4. 门 **SC0–SC4**

| # | 守卫 | 判据 | 越界后 |
| :--- | :--- | :--- | :--- |
| **SC0** | **底座核对** | 基因序匹配率 ≥ 99% 且**重算哈希**；`Gene Expression` 行数 == 18,085 且**抗体行 35 已剔**；spot 数 == `spot_mask` 的 `n_pass` | 任一不等 → **硬停** |
| **SC1** | **参数已冻结且 HMM 真在跑** | `cutoff/cluster_by_groups/HMM/denoise` 四个值与 §3.3 逐位相同；**日志中必须出现 rjags 实际被调用的证据**（不得静默降级成 `HMM=FALSE`） | 对不上或静默降级 → **硬停** |
| **SC2** | 🔴 **锚可复算**（**本臂第一道硬门**） | 同一锚集合、同一输入，**重复 N≥3 次**，逐 spot 恶性判定的**一致率 ≥ 95%**，且**每次的锚细胞/spot 名单逐字节相同** | **不一致 → 硬停，本臂到此为止，如实上报"锚不可复算"**（这正是单细胞臂的失败模式，不许绕过） |
| **SC3** | **阴性对照** | ①锚内 spot 自己必须判为非恶性（自洽）；②锚内**留出**一部分 spot 不进参考，其恶性率须与进入参考的部分**无显著差** | 锚自己判成恶性 → 锚定义错 → **硬停** |
| **SC4** | **逐切片/逐患者上报，不设通过率阈值** | 每患者报：送进的上皮 spot 数 / 锚 spot 数 / 恶性 spot 比例 / 各染色体均值；**并单列"未定义"档** | **不硬停**；**不许**事后挑患者（法则 3.2） |

⚠️ **SC4 的"未定义"必须单列**：`infercnv` 与 CopyKAT 一样会有判不了的档。
**不得**把"未定义"并进"非恶性"——那是把测不出当成测到了。

---

## 5. 与其它臂的联动

### 5.1 依赖 RCTD（单向）

```
Visium 表达 ──[SPATIAL_QC]──→ spot 掩码
                  │
                  ├─[RCTD]──→ 逐 spot 细胞类型权重 ──→ 上皮 spot 子集 ──┐
                  │                                                    ↓
                  └───────────────────────────────────→ [infercnv] ──→ 逐 spot 恶性
                                                                        │
                  病理线（PLIP）──→ 仅切片级组织密度，**不得**供标签 ────┘
```

**要点**：CNV 吃 RCTD 的**上皮 spot 子集**（一个集合），**不吃** RCTD 的恶性判断（RCTD 没有）。

### 5.2 硬禁令（继承 `SPATIAL_QC_PREREG.md` §5.2 裁决 5）

🔴 **禁止**把「CNV 的逐 spot 恶性判定」乘「RCTD 的逐 spot 上皮权重」得到"恶性细胞数/恶性比例"。
理由不变：那是**跨定义的量纲外推**。CNV 的判定单位是 **spot**，RCTD 的权重单位是 **spot 内的比例**；
相乘得到的东西**既不是 spot 数也不是细胞数**，没有对应实体。

### 5.3 与已废弃的单细胞 CNV 臂的关系

- 单细胞 CNV 的三条线（CopyKAT 锚定臂 / SCEVAN 臂 / infercnv 冒烟）**全部退出**，
  在本臂报告里一律记 **RETIRED / NOT RUN**，**不得**记作阴性证据、**不得**与本臂结果合并。
- 唯一被继承的是**教训**（§0.1）与**工具链**（§2.3 的基因序、§3.2 的环境）。
- ⚠️ 既有 `results/03_cnv/infercnv_smoke/`（P4，snRNA，`HMM=FALSE`）的
  **AUROC 0.6524「弱信号」**是**单细胞**上的数，**不得**当作本臂的先验或预期值。

---

## 6. 本臂**不**产生的结论

- 不产生**亚克隆结构 / 系统发育树**（原文后续目标，本臂不碰）
- 不产生**克隆与分期的关系**（同上）
- 不产生**逐细胞**的恶性判定（本臂的单位是 **spot**）
- 不产生**空间邻域 / 生态位**结论（属 M6 及以后）
- 不产生**预后 / 生存**结论
- 不把**未定义**档读成"非恶性"
- 不把本臂结果与**已废弃的**单细胞 CNV 结果做一致性比较

---

## 7. 待签字（**只有这几项**）

| # | 事项 | 位置 | 现状 |
| :---: | :--- | :--- | :--- |
| 1 | **锚的处置方案**（§3.4 的 A / B / C ＋ 新增 D） | §3.4 | ✅ **已裁定（2026-09-25 晚）：多锚并列，C 主 ＋ D 对照；A、B 本次 NOT RUN ⇒ 见 §11.2** |
| 2 | **上皮 spot 子集定义**（粗/细 RCA 参考、类目清单、权重阈值、未达标 spot 的处置） | §2.2 | ✅ **已裁定（2026-09-25 晚）：粗版 `a` ／ 单类目 `{上皮}` ／ 未达标剔除且逐张上报 ⇒ 见 §11**；🔴 **权重判据已由 §12.1 改签为 `argmax == 上皮`**（原「原始上皮权重 > 0.5」已作废，§11.1 保留作记录） |
| 3 | **`spot_mask` 的三个阈值**（`MIN_UMI_SPOT` / `MIN_GENES_SPOT` / `MAX_MT_FRAC`） | `SPATIAL_QC_PREREG.md` §3 | ✅ **已签字（2026-09-25），并已冻结落盘（该文件 §3.3）**：`500 / 200 / 0.15`，规则 `or`；并接受实测剔除 **4.97%** 而非原文 1.05%（该文件 §3.2(c)） |
| 4 | **若选 B：修订 §5.4「CNV ↔ RCTD 无共享对象」为「共享锚校验」** | §3.4 方案 B；`SPATIAL_QC_PREREG.md` §5.4 | ✅ **不适用**：用户在 §11 第 5 项选了多锚并列（C 主 ＋ D 对照），方案 B **NOT RUN** ⇒ §5.4 无需修订，也未被修订 |
| 5 | **是否纳入空转 QC 的 6 张浅切片**（剔除率 15–30%，见 `SPATIAL_QC_PREREG.md` §3.2(c)） | 输入定义 | ✅ **事实上已定（按执行落定，非另签）**：RCTD 门控 56 张**全部跑完并全部入表**（`RCTD_PREREG.md` §13.6），6 张浅切片**未剔除**。⚠️ 这是**执行结果**，不是对「该不该剔」的独立裁定；若日后要改输入集，须按法则 3.2 另起一次签字 |

---

## 8. 复现命令（**签字前跑不了**）

```bash
# 前置：SPATIAL_QC_PREREG.md 第 1 步（spot 掩码冻结）+ RCTD_PREREG.md（上皮权重）
export LD_LIBRARY_PATH=/home/eto/local/jags/lib:$LD_LIBRARY_PATH
R_LIBS=/home/eto/Rlibs/infercnv:/home/eto/R/x86_64-pc-linux-gnu-library/4.2:/usr/local/lib/R/site-library:/usr/lib/R/site-library \
  Rscript 08_spatial_deconv/<NN>_run_spatial_cnv.R
# ⚠️ <NN> 脚本尚未写。本文件不声称脚本已存在（与 ANCHOR_PREREG.md §8 同一纪律）
```

---

## 9. 本文件登记时**尚未**核实的事项

1. 空转的基因名过 GENCODE/HGNC 后的实际匹配率（snRNA 是 99.62%，空转未测）
2. `infercnv` 1.23.0 在 `HMM=TRUE` 下的**内存峰值与单患者耗时**（**未实测**）——
   本机 load average 长期 57–70，且后台有 PLIP 任务在跑 ⇒ 排期前必须先测一个患者的成本
3. 上皮 spot 子集的**规模**（若 RCTD 上皮 spot 数过少，infercnv 的 HMM 可能不稳）
4. 原文那 12 例"直接用全部正常肺上皮"的兜底是否暗示**其余患者也确实能找到纯正常克隆** ——
   我们无从知晓，**不得**假设我们的患者也能

---

## 10. 本文件**不**声称

- 不声称 SpatialInferCNV 已被安装或将被安装（§3.1 明确不引入）
- 不声称本臂会成功（单细胞臂失败了；本臂的锚问题**同样存在**，只是换了个模态）
- 不声称 `HMM=TRUE` 的结果一定比 `HMM=FALSE` 好
- 不声称原文的 1.05% spot 剔除率能被我们复现（实测 4.97%，见 `SPATIAL_QC_PREREG.md` §3.2）

---

## 11. 🔏 签字记录（2026-09-25 晚）—— §2.2 四项与 §3.4 锚全部裁定

> **本节的效力高于 §2.2 / §3.4 / §7 里与之冲突的正文。**
> 出处：用户 2026-09-25 口头裁定；由 Claude 按其原话代笔落盘，未代其决定任何未答复项。

| # | 项 | 裁定 | 出处／原话 |
| :-- | :--- | :--- | :--- |
| 1 | 门控用哪份参考（§2.2 ①） | **粗版 `caliber a`（6 谱系）** | 「用粗版 6 谱系门控（推荐）」 |
| 2 | 上皮类目清单（§2.2 ②） | **`{上皮}` 单类目** | 粗版下上皮不细分 ⇒ 本项退化，无清单可挑；细版 `d` 仍按 `RCTD_PREREG.md` §10 独立跑，**不参与门控** |
| 3 | 权重阈值（§2.2 ③） | ~~**原始上皮权重 > 0.5**（多数法则）~~ 🔴 **已作废 ⇒ 生效口径见 §12.1（改为 `argmax == 上皮`）** | 「原始上皮权重 > 0.5（推荐）」；🔴 见 §11.1 与 §12.1 |
| 4 | 未达标 spot 处置（§2.2 ④） | **剔除，剔除数量逐张上报** | 「剔除，但逐张上报数量（推荐）」 |
| 5 | 锚的处置（§3.4） | **多锚并列，报逐 spot 判定一致率**：C 主 ＋ D 对照（🔴 **C/D 各自的 spot 抽取口径已按 §12.2 改为 argmax 版**） | 「多锚并列，报一致率（推荐）」；🔴 见 §11.2、§12.2 |

### 11.1 ~~为什么阈值能写成「权重 > 0.5」~~ 🔴 **本节已作废，保留作记录**

> 🔴 **2026-09-25 晚**：§11 第 3 项那条「原始上皮权重 > 0.5」**已被 §12.1 改签为
> `argmax == 上皮`**。本节当初是为 `> 0.5` 辩护的，**其结论已被实验推翻**，
> **不得再被引用为门控口径的依据**。保留下来的原因是：它记录了「为什么会写成 0.5」，
> 以及那个合成实验错在哪 —— 那正是 §12.1 改口径的起点。

§M5 的禁令（`RCTD_PREREG.md` §1、G4）禁的是**把 Σ=1 的归一化当门**。
被改签的口径**当时**也**不触碰**它：判据取 `results$weights` 的**原始**上皮列，
代码里**不出现** `normalize_weights()`（这一点在 §12.1 的新口径下**仍然成立**）。

当年支撑这条写法的实测（脚本 `08_spatial_deconv/probe_rctd_weight_scale.R`，
合成数据 3 类型 × 10 spot、纯类型 spot 对纯类型参考；`spacexr` 2.2.1、`max_cores=1`）：
权重矩阵是 **spot × 细胞类型**；纯类型 spot 的自类型权重 **0.93–0.98**、逐 spot 行和 **0.88–0.99**；
把同一批 spot 计数整体 ×2（构成一字不改）权重几乎不动（0.962→0.953、0.982→0.979）。
⇒ 当时读作「**原始权重就在『约等于比例』的量纲上，且不随测序深度漂移**」。

🔴 **上面这个「不漂移」的读法是错的，两处：**

1. **合成实验里 ×2 的计数是「整份构成不变地翻倍」**，而真实切片之间差的是**每种基因各自被稀释**、
   且深度不一 —— 两类扰动**不是一回事**。合成实验**没有**测真实那类。
2. 真检验（`RCTD_PREREG.md` §13.5，`--thin 0.5` 计数减半重跑）证明：**深度变动下
   `argmax` 会移动 9.93%** ⇒ 「原始权重不随深度漂移」这个前提**实测不成立**。
   （另：把**产出权重**整体缩放而 `argmax` 不动，是**恒等式**，不能当深度不变的证据 —— 见 §13.5.1。）

🔴 当年那条守卫 **G5 已由硬门撤为报告项**（用户 2026-09-25 晚签字，见
`RCTD_PREREG.md` §4 / §13）。**撤它的理由**是：它那个统计量分不开生物学与技术（§13.1），
**不是**因为它担心的事不存在 —— 那件事是真的（§13.5）。
⇒ 本条的**结论作废**，但**记录保留**。

⚠️ **原口径的自定成分**：`0.5` 是**约定俗成的多数线**，**无文献出处**，按项目规矩标 **⚠️C**。
`RCTD_PREREG.md` §11.0 记了这段口径的来历（用户问「有文献支持吗」，答：
「用原始权重」有工具依据，「良性端 P75」里那个 75 是 Claude 拍的 ⇒ 用户改选多数法则）。
**这个自定成分正是后来改签 `argmax` 的动因之一** —— 改签后不再出现 `0.5`。

**当年的敏感性诊断承诺**（逐张给 P60 / P70 / P80 三档通过率）**已被 §12.1 的改签取代**：
新口径下阈值不存在，取而代之的是 §13.7 强制的 **margin 梯度五档复核**（§12.4 第 3 条）。

### 11.2 锚：多锚并列（C 主 ＋ D 对照）

🔴 **两次运行的观测集相同**（= §11 第 3 项的上皮 spot 子集，
🔴 **已按 §12.1 改签为 `argmax == 上皮`**），
**只有参考集不同**。这样比出来的差异**只来自锚**，这是本设计的要点。
⚠️ 但见 §12.4 第 3 条：该观测集在深度变动下 **Jaccard 仅 0.840**，翻转集中在并列处 ——
锚正是从这些集合里取的 ⇒ **每条主要结论必须带 margin 梯度复核**。

- **C（主）**：**良性切片**（Normal / AAH）中 **`argmax == 上皮`** 的 spot。
  **同患者优先**；该患者无良性切片时借**队列良性端**，并在报告里**逐患者标明是借的**
  —— §3.4 方案 C 已登记的「患者间锚定义不一致」风险由此**显式化**，不隐藏。
  选锚只用**分期标签**、**完全不看 CNV** ⇒ 无 §3.4 方案 A 的循环论证。
- **D（对照）**：**非上皮主导 spot** —— 成纤维 / 髓系 / T·NK / 内皮 / B·浆 五个非上皮类型
  **任一为 `argmax`**（与门控**同一条判据 `argmax`，方向相反**）。
  完全不用任何标签、也完全不看 CNV。
  🔴 **已知弱点**：锚与观测**谱系不同**，infercnv 会把「细胞类型差异」算进 CNV 里
  ⇒ **D 只能与 C 并列看一致率，不得单独下结论，也不得事后挑好看的那组**（法则 3.2）。
- **锚的合并单位**：**按患者**（§2.1：切片按患者合并），C、D 各自逐患者确定名单。

**A、B 本次 NOT RUN**：A 的循环论证风险未解（无参模式基线是全体 spot 均值，肿瘤为主时
「最低 CNA 的克隆」可能仍是肿瘤）；B 需单独改签 `SPATIAL_QC_PREREG.md` §5.4
⇒ 本次不启动。两者**不得**被读成「未被证伪」（本文件 §10 已列明「不声称」的范围）。

⚠️ **D 是本项目首次**（原文用正常肺上皮作参考）。若 C 与 D 的一致率低，
**先怀疑 D 的谱系错配**，不要先怀疑 C。

### 11.3 本节**不**声称

- 不声称 `0.5` 有文献出处（§11.1 明标 ⚠️C）。
- 不声称多锚一致率**高**就等于恶性判定正确 —— 一致只排除「锚换一个结论就变」这一种失效。
- 不声称 D 的谱系错配无害（§11.2 已写明其已知弱点）。
- 不解除任何既有禁令：**恶性 × 权重**的乘法禁令（§5.2）**不变**。
- 未变项：`spot_mask` 三阈值（§7 第 3 项）与 6 张浅切片是否纳入（§7 第 5 项）**已按
  `SPATIAL_QC_PREREG.md` §3.3 签字**（500 / 200 / 0.15、全 56 张）。

---

## 12. 🔏 签字记录二（2026-09-25 晚）—— 门控阈值改为 `argmax == 上皮`

> **本节的效力高于 §2.2 / §11 里与之冲突的正文。**
> 出处：用户 2026-09-25 裁定；由 Claude 按其原话代笔落盘，未代其决定任何未答复项。

| # | 项 | 裁定 | 出处／原话 |
| :-- | :--- | :--- | :--- |
| 1 | 上皮 spot 子集的门控阈值（§2.2 ③，**作废 §11 第 3 项**） | **改为 `argmax == 上皮`**：该 spot 的权重最大的一类就是上皮 | 「改成 argmax（推荐）」 |
| 2 | 随之改动 C / D 两锚的 spot 抽取口径 | **C** = 良性切片中 `argmax == 上皮` 的 spot；**D** = `argmax != 上皮` 的 spot（**本轮由 Claude 依同一实测顺延推出**，见 §12.2） | 由第 1 项直接顺延；用户未单独答复，**可撤回** |

### 12.0 这段口径是怎么改的（留痕）

阈值这一项**在 §11 已签过**（`> 0.5`）。改它不是因为不喜欢结果，是因为
**实测发现它和它自己挂的标签对不上**，而它挂的标签正是用户当初选它的理由。

冒烟测试（单张 `GSM9226168_P1_AAH`，粗版参考，`01_run_rctd.R` 实跑）实测：

| 量 | 实测 |
| :--- | :--- |
| 上皮权重 中位 / P90 / P95 / 最大 | **0.295** / 0.430 / **0.517** / 0.806 |
| 逐 spot 行和 分位（0/25/50/75/100） | 0.577 / 0.894 / **0.926** / 0.953 / 1.062 |
| `> 0.5` 保留 | **577 spot（5.8%）** |
| `argmax == 上皮` 保留 | **4,745 spot（48.1%）** |
| P60 / P70 / P80 三档诊断（§11.1 约定的报告项） | **0.316 / 0.340 / 0.371** |

📌 **2026-09-25 晚更正**：本表原先是按 **9,932 spot** 的一份中间稿算的
（`> 0.5` 582 / 5.9%，argmax 4,758 / 47.9%，行和上界 1.089，多数线切留 8.4%）。
实测那 9,932 是**正确答案 9,870 的超集**（多 62 个，一个不少），多出的 62 个上皮权重
**中位 0.001、最大 0.043**，全在分布最底部 ⇒ **分位与两条线的位置完全没变**，
但**计数**会动：上表已按正式产物 `results/08_spatial_deconv/rctd_a/per_slide/
GSM9226168_P1_AAH.weights.tsv.gz`（9,870 spot）**逐项重算**。判读不受影响。
（同一件事的登记见 `RCTD_PREREG.md` §12.5 第 5 项。）

**两条判读**（都是图上直接看得出来的，不是推断）：

1. `0.5` **不是**「多数线」。行和中位 **0.926 ≠ 1** ⇒ 真正的多数线是 `0.5 × 0.926 ≈ 0.463`。
   但这不是主要差距：按 `0.463` 切也只留 7.6%。
2. 主要差距在**分布形状**：一个 55 µm 的 Visium spot 里含多类细胞，六谱系分成 ~0.93、
   平均每类 ~0.15。上皮拿到 **0.30 就已经是该 spot 里最大的一类**，却离 0.5 很远。
   ⇒ `0.5` 的实际含义是「上皮**单独一种**就占整张 spot 信号的一半以上」，
   落在该权重的 **P95 附近**，几乎是空集。**「多数法则」这个标签名不副实。**

诊断图（参数问题按项目规矩给图）：
`results/08_spatial_deconv/rctd_a/fig_epi_weight_threshold_smoke.png`
（左 = 权重分布与各阈值线；右 = 保留比例随阈值的变化曲线）

### 12.1 生效口径

- **判据**：对每个 spot 取 `results$weights` 行内**最大的一类**（argmax）；**最大类 == 上皮** 即入子集。
- 🔴 **自定参数消失**：`0.5` 这个 ⚠️C 无出处的数字**整个消掉**，本口径**零阈值**。
  这是改口径的**附带收益**，不是改口径的理由（理由见 §12.0）。
- **仍不触碰 §M5/G4**：argmax 只用**原始权重列之间的大小关系**，
  **不做**逐 spot 归一化，代码里仍**不出现**被禁的归一化调用。§11.1 的合规论证**继续成立**。
- **并列情形（登记）**：若一个 spot 有两类**权重完全相同且并列最大**，判为**未达标**（剔除并计数）；
  **不做**随机打破、**不做**按类型名排序打破（两者都会偷偷引入偏好）。实测该情形
  **尚未出现**，出现时逐张上报数量。

### 12.2 锚的定义随之改动（🔴 本轮由 Claude 顺延推出，**可撤回**）

C、D 两锚的 spot 抽取在 §11.2 里写的是同一条 `0.5`（C 正方向、D 反方向）。
该 `0.5` 与 §12.0 被作废的是**同一个数、同一个毛病**（实测 D 侧 `非上皮 ≥ 0.5` 只留 **1.7%**）。
若只改 C 不改 D，两次运行比出来的**一致率会失真**（两个观测集的定义口径不同源）。

故顺延为：

- **C（主）**：**良性切片**（Normal / AAH）中 `argmax == 上皮` 的 spot。
  **同患者优先**；借队列良性端者**逐患者标明**（§11.2 不变）。
  选锚只用**分期标签**、**完全不看 CNV**（§11.2 不变）。
- **D（对照）**：`argmax != 上皮` 的 spot（即最大类落在成纤维 / 髓系 / T·NK / 内皮 / B·浆）。
  完全不用任何标签、也不看 CNV（§11.2 不变）。
- 🔴 **§11.2 已写明的 D 的已知弱点（谱系错配）不变**：只能与 C 并列看一致率，
  **不得**单独下结论、**不得**事后挑好看的那组。

⚠️ **这一项用户没有单独答复**，是 Claude 依 §12.0 的同一条实测**顺延推出**的；
若用户认为 D 应保留独立的 `0.5` 反面口径（承担两次运行口径不同源的代价），**可以撤回本项**。

### 12.3 本节**不**声称

- 不声称 `argmax` 一定**更好**或**更准**；只声称它**与「上皮是最大的一类」这个语义一致**，
  且**消掉了一个无出处的自定数字**。
- 不声称 argmax 子集里的 spot 是**纯上皮**。🔴 **2026-09-25 晚更正本句的两个数**：
  初稿写「子集内上皮权重 ~0.30、其余各类 ~0.20」——**那两个数对不上**（`~0.30` 其实是
  **整张切片**的上皮权重均值，不是子集内的）。
  按 RCTD 56/56 实跑逐张复算（`results/08_spatial_deconv/rctd_a/per_slide/*.weights.tsv.gz`），
  **`argmax == 上皮` 的子集内**：上皮权重均值**逐张中位 0.438**（范围 0.357–0.584），
  **其余五类各自的均值逐张中位仅 0.095**（范围 0.067–0.115）。
  ⇒ **结论方向不变**（仍是混合 spot、上皮只占相对多数），但**数要按这一版**：
  子集内上皮约 **0.44 vs 其余每类约 0.10**，不是 0.30 vs 0.20。§11.3 的保留意见不变。
- 不解除任何既有禁令：**恶性 × 权重**的乘法禁令（§5.2）**不变**；RCTD 权重**不得**读作恶性判定。
- **不改**法则 3.2 的适用方向：本节（§12.1）是一次**签字前的**口径更正
  （🔴 更正一句：当时写的「全队列尚未跑完」**已过时** —— RCTD 56 张已于 2026-09-25 晚跑完，
  见 `RCTD_PREREG.md` §13.6；但**本节的更正发生在那之前**，且**CNV 至今未跑**，
  所以此更正**仍是「事前」的**，不是在 CNV 结果上回头调）。
  **CNV 一旦开跑，本条即冻结** —— 至今未开跑，故仍然有效。

### 12.4 本口径的守卫 G5 已退休（2026-09-25 晚，用户签字）

§11 第 2 项给本口径挂过一个深度守卫 **G5**（逐张 `|Spearman(原始总 UMI, 权重行和)| ≤ 0.5`
硬停），用来保证「阈值含义不随深度改变」。**该守卫已于 2026-09-25 晚撤为报告项**，
全跑时它第 2 张就硬停（`rho = 0.521`）。

**理由（一句话）**：G5 守的是被本节**作废掉的那条绝对阈值**；现行口径 `argmax == 上皮`
比的是**权重列之间的大小、不是绝对值** ⇒ 与「阈值取多少」这件事本来就无关。

🔴 **2026-09-25 晚更正 —— 原来这里写的理由有一处推理错误，已撤**：
原文写「对整体尺度**构造上不变**（实测权重 ×0.5 / ×2.0，`argmax` 变动 0 个 spot）」。
那句话**本身没错，但它说的是把产出权重整体乘常数** —— **恒等式，与测序深度无关**。
后来补做的真检验（**把计数减半、让 RCTD 重新估计**）结果完全不同：
**`argmax` 移动 9.93%、门控判据翻转 8.30%**，两组上皮集合 **Jaccard 仅 0.840**。
⇒ **该守卫的守卫对象并没有「不存在」**；撤掉 G5 只是撤掉一个**测不准的仪表**。
完整结果、更正与用户裁定（当时为**口径先不动，等 56 张跑完再定** —— 🔴 56 张已跑完，
**最终处置见下方 §12.4 末**，即「口径不动 ＋ 敏感性复核」）见 `RCTD_PREREG.md` §13.5。

完整诊断（六条证据，含「它其实测的是 mRNA 总量 vs 分到细胞质量」「深度在空间上成组织样团块」
「阈值 0.5 落在观测范围内且不能跨切片比」）与一次**真检验**的设计，见
`RCTD_PREREG.md` **§13**；诊断图 `results/08_spatial_deconv/rctd_a/fig_g5_diagnosis.png`。

⚠️ **本节不改动 §12.1 的门控口径本身**（仍是 `argmax == 上皮`），只是撤掉它的一个守卫。
⚠️ **不声称** `argmax` 因此一定准 —— 真检验结果见上，**在并列附近它确实不稳**。

🔴 **要跟着结论一起报的一个数**：上皮 spot 集合在**深度减半**下 **Jaccard = 0.840**
（**出 439 / 进 380**，方向基本对称，抖动集中在并列处；`margin ≥ 0.15` 的 2,516 个 spot 零移动）。
不同切片深度不同 ⇒ **各张的「上皮 spot 集合」不是同一把尺子量出来的**。
这对本节 §12.2 的**多锚设计（C 主 + D 对照）**是要害：**锚正是从这些集合里取的**。
⇒ 在用户就 §13.5.4 备选处置签字之前，**不得**用这些集合去建锚、也**不得**声称跨切片可比。
🔴 **该冻结已于 2026-09-25 晚解除** —— 见紧接的下一段（用户签字：口径不动 ＋ 敏感性复核）。

🔴 **该处置已于 2026-09-25 晚签字：口径不动 ＋ 敏感性复核**（逐字裁定与完整条款见
`RCTD_PREREG.md` **§13.7**）。对本节的三条直接后果：

1. **门控口径不变**：仍是 `argmax == 上皮`，**一个数都不新签**，margin 不进任何筛选；
2. **建锚解冻**：§12.2 的多锚设计（C 主 + D 对照）**可以开始取**，用已签口径；
3. **但每一条主要结论都要带一条 margin 梯度复核**（§13.7 第 3 条）——
   `margin ≥ 0.15` 时单张实测**零移动**，可作为最干净的一档，但**只作复核网格、不作门控**。

---

## 13. 🔏 签字记录三（2026-09-27）—— `analysis_mode` 矛盾裁定：取 `samples`，关绘图，单患者重测

> **本节的效力高于 §3.3 正文里与 `analysis_mode` 相关的那句。**
> 出处：用户 2026-09-27 裁定；由 Claude 按其选项代笔落盘，未代其决定任何未答复项。

### 13.1 裁定

| # | 项 | 裁定 |
| :-- | :--- | :--- |
| 1 | §3.3 那句「本臂**不**继承 `analysis_mode="subclusters"`」与工具默认值的矛盾 | **取 §3.3 这一边**：`analysis_mode = "samples"` |
| 2 | 绘图 | **`no_plot = TRUE`**（关掉；§3.3 未记此项，属未记项，不构成对原文的偏离） |
| 3 | 成本冒烟 | **重跑，限单患者**；成本数字拿到之前不谈队列排期 |

**第 1 项的理由（不是"结果不好看"）**：原文方法段**只记了 4 个参数**、未记 `analysis_mode`
⇒「未记项取工具默认」是一种读法；但 §3.3 是**本臂自己白纸黑字**写了不继承，而默认值那一边
没有任何别的依据。两者只能取一，取本臂已登记的那一边。

### 13.2 促使本次裁定的实测（`logs/detached_20260925/step1_cnv_smoke_P4.log`）

患者 P4（2 张切片）在**工具默认** `analysis_mode="subclusters"` + `HMM=TRUE` 下，
**24 小时未跑完**，被 1440 分钟超时杀掉（`exit 124`）。**峰值内存只有 7.67 GB ⇒ 不是内存问题。**

| 阶段 | 耗时 | 备注 |
| :--- | :--- | :--- |
| 建对象（17,272 基因 × 34,333 spot，10,627 观测 + 23,706 参考） | **2.7 分钟** | 峰值 7.67 GB |
| STEP 10 平滑 | ~12 分钟 | |
| STEP 17 HMM | **46 分钟** | 06:47:31 → 07:33:36 |
| 画热图 | **9.5 小时** | 07:34 → 17:07（**纯绘图**） |
| STEP 18 贝叶斯网 MCMC | **未完成** | 17:09:12 起，20:17 被杀 |

**根因**：`subclusters` 把参考切出 **181 个亚群**、观测 65 个 = **246 个单位**，
HMM 与贝叶斯网**按单位逐个跑**。取 `samples` 后单位数降到 **2**。

### 13.3 两条**必须一并钉死**的（否则返工）

1. 🔴 **per-spot 判定取自哪个产物**：SC4 要「逐 spot 恶性比例 + 单列未定义档」，
   但**本预注册从头到尾没写**这个判定读 infercnv 的哪个文件、哪一列。
   ⇒ **签名时应一并登记**；在登记之前**不得**开始判 SC4。
2. 🔴 **SC2（锚可复算）是第一道硬门，且从未被测过**。所以第一炮**必须是单患者**，不得上队列。
   SC2 不过 ⇒ 本臂到此为止、如实上报"锚不可复算"（单细胞臂的失败模式：同一批 3,890 个锚细胞
   三次跑出 **0% / 13.6% / 49.8%**）。

### 13.4 本节**不**改动的东西

- §3.3 的四个参数（`cutoff=0.1` / `cluster_by_groups=TRUE` / `HMM=TRUE` / `denoise=TRUE`）**一字不改**；
  **`HMM` 仍是 `TRUE`**（本次只改 `analysis_mode`，不是退到 `HMM=FALSE`）。
- 门 **SC0–SC4** 一字不改；§11.2 的多锚设计（C 主 + D 对照）一字不改；§12.1 的 `argmax == 上皮` 一字不改。
- `no_plot` **只影响出图，不影响任何判定**（图不是结果）。

### 13.5 本节**不**声称

- 不声称 `samples` 的结果一定与 `subclusters` 一致（**未测**；这是本臂的一处**未做的等效性检验**，如实登记）。
- 不声称成本问题已解决 —— **§9 第 2 项至今只有负答案**（"默认模式下最大患者 24 h 跑不完"），
  取 `samples` 后的真实墙钟/内存**尚未实测**。
- 不声称贝叶斯网（STEP 18）对 SC2–SC4 是必需的 —— 逐 spot 判定来自 HMM 那一步；
  但 `infercnv::run` **未暴露**跳过 STEP 18 的开关（`formals` 已查），故只能让它跟着跑。

### 13.6 附带登记的缺陷（不在本臂判据内）

队列脚本 `scripts/queue_detached_20260925.sh` 的**失败上报**有 bug：冒烟超时后报
`KeyError: 'elapsed_min_run'`（`queue.log`）。日志确实写了失败、队列也继续跑了第 2 步，
但失败账目本身崩了。⇒ **下轮脱离式跑之前须修**，否则失败不可清点。

**根因（2026-09-27 查明）**：哨兵判据（`queue.sh` 第 97–101 行）要求 manifest 里**有**
`elapsed_min_run`，但失败后的打印（第 115 行）只判 `[ -f "$M1" ]` —— 而
`results/.../smoke_P4/smoke_P4_manifest.json` 从**上一轮 `--object-only` 验证**就在那儿
（那份不含 `elapsed_min_run`）。⇒ 超时后文件仍在，打印分支照样进，读键即崩。
**修法**：打印前也判键，不判文件。✅ **2026-09-27 已修**（该脚本与新的
`scripts/queue_detached_20260927.sh` 均用同一个 `has_run()` 判据）。

---

## 14. 🔏 签字记录四（2026-09-27）—— 原文源码核对：三处偏差，`chr_exclude` 改签为 `c("chrM")`

> **本节的效力高于 §3.1 / §3.3 正文里与本节冲突的部分。**
> 出处：用户 2026-09-27 指令「去做」，对 Claude 同日提出的三处偏差逐条裁定。
> 由 Claude 按其裁定代笔落盘，**未代其决定任何未答复项**（§13.3 第 1 项仍未签，见 14.5）。

### 14.0 促成本次核对的起因

用户 2026-09-27 提问：「我的 cnv 不是用的空间 cnv 优化吗，你是不是用单细胞级的给我做了」。
为回答该问题，Claude **首次**把原文 `SpatialInferCNV` 仓库（github.com/aerickso/SpatialInferCNV）
的**源码**逐字拉下来核 —— 此前 §3.1 的依据只是「仓库无 LICENSE」这一条 README 层的观察。
核对结果同时暴露了本臂的**三处偏差**，本节即此三处的裁定与登记。

### 14.1 核对结果：原文的「空间优化」不是算法

| 核查项 | 事实 |
| :--- | :--- |
| `R/` 目录（**11 个函数**，逐个看过） | 全部是「读 Visium 数据 / 读注释 / 合并 / 在 infercnv 树上选节点 / 画图」 |
| `DESCRIPTION` | `infercnv` 列为依赖 |
| `README` | 明写 "the `infercnv::run` analyses steps" |
| `FigureScripts/` | 只有 Rmd + 图 + **手写的**克隆 CSV（见 14.2） |

⇒ 原文的 CNV 引擎**就是 `infercnv`**，与本臂**同一台**。
所谓「空间优化」= **外围管道**（谁进 CNV、谁是参考、克隆怎么定），
**不是** CNV 算法；**没有** spot 平滑、**没有**反卷积输入、**没有**空间邻域项。

### 14.2 原文的完整判定链（Step1/2/3，逐字取自源码）

| 步 | 代码要点 | 关键参数 |
| :--- | :--- | :--- |
| Step1 无监督建树 | `CreateInfercnvObject(..., ref_group_names="Purest Benigns", chr_exclude=c("chrM"))` → `run(...)` | `cluster_by_groups=FALSE`、**`HMM=FALSE`** |
| Step2 手工聚类 | 读 `infercnv.observations_dendrogram.txt` → `as.phylo` → `subtrees()` → 画树带节点号 → **人工手挑 14 个节点 → 11 个克隆 A–K** | — |
| Step3 带 HMM 出结果 | 用 Step2 的克隆标签当组，`CreateInfercnvObject(...)` → `run(...)` | `cluster_by_groups=TRUE`、**`HMM=TRUE`** |

**「哪些 spot 进 CNV」在原文里是病理注释给的**（Loupe Browser 手工分级，逐字）：
```r
H1_2_CancerSpots <- filter(H1_2_Annotations, Histology == "GG1")
H1_5_CancerSpots <- filter(H1_5_Annotations, Histology == "GG4 Cribriform")
```
**「哪个 spot 属于哪个克隆」是人工看树定的** —— Fig2/Fig3 的 spot→克隆表是仓库里
**手写的 CSV**（`FigureClone_A/B/C/F`），仓库内**没有**生成它的脚本。

⇒ 🔴 **原文的恶性/克隆判定是人工的**（病理注释 ＋ 人工挑树节点），不是算出来的。

### 14.3 由此产生的三条裁定

| # | 项 | 裁定 |
| :-- | :--- | :--- |
| 1 | **`chr_exclude`** —— 原文 Step1/Step3 **两处都显式写了** `c("chrM")`，而本臂用了 infercnv 默认 `c("chrX","chrY","chrM")` | ~~**改签为 `c("chrM")`，照原文**~~ 🔴 **2026-09-29 二次改签（见本行下方）** |
| 2 | §3.3 抄的「原文四参数」实际是原文 **Step3（第二遍 run）** 的参数；其前还有 Step1 ＋ 人工聚类，而本臂是**单遍** run | **只登记，不改计算** |
| 3 | 原文两遍 `run()` **都没有写** `analysis_mode` ⇒「原文用的是 `subclusters`」**不是原文写的**，是包默认 | **只登记，不改计算**；§13 的裁定**不受影响**（§13 的理据是 §3.3 本臂自记，不是「原文用过」） |

**第 1 项的理由**：本臂 §3 的整个前提是「逐字照抄原文」。`chr_exclude` 是原文**记了的**
参数（记在**代码**里，不是方法段里），我们此前当成「未记项取默认」处理 —— 这与 §13 那处
`analysis_mode` 是**同一类错、方向相反**：`analysis_mode` 原文**没记**，取默认有理；
`chr_exclude` 原文**记了**，取默认就是偏离。

**第 1 项的代价与配套守卫**：`c("chrM")` 把 chrX/chrY 放回管线
（基因账 **17,272 → 18,004**，多 **732** 个：chrX **716** ＋ chrY **16**）。
原文 Fig2 是**单患者**（Patient 1，7 张切片），同一个体性别恒定 ⇒ chrX/Y 不引入性别假象。
**本臂的 C 主锚是「同患者优先」，无良性切片时按 §11.2 借队列良性端（跨患者）**
⇒ 借锚的病例上，chrX/Y 会把**男女剂量差**算成 CNV。
⇒ 配套守卫（与第 1 项**一并生效**）：
**逐患者报告「参考与观测是否同患者」；凡跨患者借锚者，其 chrX/Y 相关结论一律降级为「待定」。**
冒烟脚本已在 manifest 里记 `ref_same_patient` 与 `ref_slides` 供此事后核。

> 🔴🔴 **第 1 项二次改签（2026-09-29，用户签字）—— 因 §18 换引擎**
> **生效口径改为：本臂有效染色体范围 = 常染色体 ＋ chrX；`chrY` 与 `chrM` 排除在外。**
> **理由**：引擎换成 fastCNV 后，工具**源码里硬编码**只留
> `chromosome_name %in% c(1:22,"X")`（§15.8 第 1 项，2026-09-29 源码级复核**仍成立**）
> ⇒ chrY/chrM **一律不在信号内**，这不是我们选的，是工具的性质。
> 与其留一条与实际不符的旧口径（读者会以为 chrY 还在），不如改签承认。
> **配套守卫随之收窄**：§14.6 那条「跨患者借锚 ⇒ chrX/Y 结论降级」**改为只针对 chrX**。
> ⚠️ **不得**把这条读成「性别混淆问题解决了」—— chrX 仍在信号里，
> 借异性别锚的 chrX 剂量混淆**依然存在**（详见 §18.4 末尾的反直觉细节）。
> ⚠️ 本条是对**原文**（`c("chrM")`，chrY 保留）的**进一步偏离**，与 §18.2 的
> 「不再复现原文」是同一笔账，**须一并如实登记**。

### 14.4 本节**不**改动的东西

- §3.3 的四个参数（`cutoff=0.1` / `cluster_by_groups=TRUE` / `HMM=TRUE` / `denoise=TRUE`）**一字不改**。
- §13 全部裁定（`analysis_mode="samples"`、`no_plot=TRUE`、单患者成本重测）**一字不改**。
- 门 **SC0–SC4**、§11.2 多锚（C 主 ＋ D 对照）、§12.1 的 `argmax == 上皮` **一字不改**。
- §3.1「不引入 SpatialInferCNV 本体（无 LICENSE）」**仍然成立** —— 本节只是补上
  「即便有 LICENSE，它也不含 CNV 算法」这一事实，**不**构成引入它的理由。

### 14.5 本节**不**声称

- 不声称「本臂复现了原文的恶性判定」—— 原文是**人工**判的（14.2），本臂是**自动**的。
  报告里的准确措辞是：**「同引擎、同参数；判据层不同（原文人工 / 本臂自动）」**。
  **不得**写「按原文方法判恶性」。
- 不声称 `chr_exclude=c("chrM")` 在本队列上无害 —— 见 14.3 的跨患者借锚守卫。
- 不声称 §13.3 第 1 项（per-spot 判定取自哪个产物）已解决 —— **该项仍未签字**，
  本节不涉及；在它签字前 **SC4 不得开始**。
- 不声称原文的两遍结构（`cluster_by_groups=FALSE` → 人工 → `TRUE`）已被本臂吸收 ——
  本臂是单遍（14.3 第 2 项）。

### 14.6 本节附带登记的缺陷（不在本臂判据内）

`11_run_spatial_cnv_smoke.R` **尚未实现** §11.2 的「借队列良性端」锚路径：遇
`n_ref == 0` 直接 `stop()`（约第 149 行）。⇒ 本臂目前**只能跑自带 Normal|AAH 切片的患者**
（队列 25 个里 **10** 个：P1/P2/P4/P6/P9/P11/P20/P22/P24/P25）。这一条与 14.3 的 chrX/Y
守卫是**同一件事的两面**：借锚一旦实现，性别混淆才真正被引入。

> 🔴 **2026-09-29 收窄**：因 §18 换引擎且 §14.3 二次改签，本守卫**只针对 chrX**
> （chrY 已因工具性质不在信号内）。**同性别配对仍然必要**（chrX 剂量差照样会造假信号），
> 只是少了一半理由。见 §14.3 的二次改签框与 §18.4 末尾。
⇒ 借锚口径须**单独签字**后方可实现；未签字前不得实现、不得排全队列。

---

## 15. 🔏 签字记录五（2026-09-29）—— 换引擎提案 + fastCNV 单患者**体检**（不替换 §3）

### 15.0 促成本次的实测与用户裁定

**实测（本节写之前刚量到的）**：§13 那次单患者成本冒烟（`logs/detached_20260927/`）
**已于 2026-09-28 07:44 跑完**：

| 项 | 值 |
|---|---|
| 总用时 | **990.2 min（16.5 h）** |
| 其中 STEP 15「Clustering samples」 | **493.5 min（50%）** |
| 其中 STEP 18「Bayesian Network」 | **464.9 min（47%）** |
| STEP 10 平滑 / STEP 17 HMM | 13.9 min / **6.4 min** |
| 峰值内存 | **46.04 GB** |
| 进管线基因 | 18,004（`chr_exclude = chrM`） |

⇒ **§13 改 `analysis_mode="samples"` 只把 HMM 从 46 min 压到 6.4 min，成本没解决**：
烧掉 97% 时间的聚类与贝叶斯网两步**不吃这个参数**。按此速率 25 患者约 **17 天**。

**用户裁定（2026-09-29）**：
1. 「先跑单切片冒烟体检」——**不替换** §3，先拿事实。
2. bioRxiv 预印本出处「可以接受，如实标注」。

### 15.1 本节是什么，**不是**什么

**是**：对候选替代工具 `fastCNV` 做一次**单患者（P4，4 张切片）体检**，
回答三个**工具层面**的问题（15.3 的 V1/V2/V3）。

**不是**：本节的任何产物**不构成恶性判定**，**不得**用于 SC0–SC4 任何一门，
**不得**据此产生任何 spot 级恶性标签。「恶性」判据仍未签字（§13.3 第 1 项）。

### 15.2 工具与出处（**如实标注**）

- 包：`fastCNV` v1.1.11，**License GPL-3**（出处清白，与 §3.1「SpatialInferCNV 无 LICENSE」相反）。
- 出处：Cabrejas G., Sroussi M., Croizer H., Cazelles A., Salaün N., Jerman L., Hirsch T.Z.,
  Mouillet-Richard S. *FastCNV: fast and accurate copy number variation prediction from
  high-definition spatial transcriptomics and scRNA-seq data.*
  **Genome Medicine**（ISSN **1756-994X**），DOI **`10.1186/s13073-026-01731-w`**，
  Springer Science and Business Media LLC，**published online 2026-08-29**，许可 **CC BY-NC-ND 4.0**。
  ⇒ **已经同行评审、已正式发表**（Crossref 逐字段核验，2026-09-29）。
  ⚠️ 准确说法：venue 是 **Genome Medicine**（Springer Nature / BMC 旗下），
  **不是 Nature 品牌刊**；Europe PMC 对应该 DOI **0 命中**（尚未收录，属 "Article in Press"），
  可检索到的只有预印本 **bioRxiv 2025.10.22.683855**。
  ⚠️ 新版本（工具 **v1.1.11**）另见 GPL-3 源码：<https://must-bioinfo.github.io/fastCNV>。

> 🔴🔴 **本节初稿的登记是错的（Claude 的错，2026-09-29 更正）**
> 初稿写的是「bioRxiv 2025.10.22.683855 …… 🔴 **是预印本，未经同行评审**」。
> **实际上期刊版 2026-08-29 就已上线，比本节签字（2026-09-29）早一个月。**
> 我登记时只查了 Europe PMC（未收录 ⇒ 只回预印本）就下了结论，
> **没有查 Crossref**。经用户指出「fastcnv 是正刊的文章吧」后复核，**用户是对的**。
> ⇒ 凡先前据「未经同行评审」推出的一切推论（尤其 §15.5 的「不替换」部分理由）
> **一律作废重判**。原文保留不删，作为登记错误的存证。
- 本机实测：`R_LIBS=/home/eto/Rlibs/fastcnv` 下可装载（Seurat 5.0.1 ＋ Banksy 0.1.6），
  内置基因表 **Ensembl v113**，`getGenes()` 默认走缓存 ⇒ **不需要联网**。
- **它的算法与 `infercnv` 属同一族**：逐基因 `log2(1+counts)` → 中心化 → **减参考均值**
  → 截断 [-3,3] → 按染色体臂切**基因组窗口（150 基因 / 步长 10）**取窗口均值
  → 把落在参考 [1%,99%] 分位带内的窗口**置 0** → 每 spot 的 `cnv_fraction` = 非零窗口占比。
  ⇒ **它快，是因为它删掉了聚类 / 贝叶斯网 / HMM 三步**（正对我们那 958 min），
  **不是因为算法更强**。凡报告速度处**必须**一并写这句，不得暗示「更好的方法」。

### 15.3 体检三项（V1/V2/V3）与各自判据

- **V1 速度**：逐段墙钟 ＋ 进程峰值内存，**与 infercnv 同患者同输入**（P4，34,333 上皮 spot）
  ⇒ 与上面的 990.2 min / 46.04 GB 直接可比。**判据**：无门槛，报数。
- **V2 自平性**（本体检的**承重项**）。分两条，**都必须做**：
  - **V2a 池化同患者参考**（＝ §11.2 的 C 主锚）：参考 = Normal＋AAH＋AAH-1 三张良性切片的
    上皮 spot 汇池；看 **LUAD** 组的 `cnv_fraction` 分布。
  - **V2b 留一自检**（**非循环的那一条**）：参考 = **只用 Normal 一张**，
    则 AAH / AAH-1 变成**被留出的良性观测**。若留出的良性组织仍判平 ⇒ 该方法在跟生物学走；
    若留出的良性也判高 ⇒ 该方法不能自证其参照。**这条是本次唯一能证伪的路子。**
  - **判据**：两条都**只报**（各组中位／四分位 ＋ **无阈值**的分离度 AUC），
    **不设门槛、不判通过与否**。
  - 🔴 **必须先声明的循环性**：参考组的 `cnv_fraction` 由构造必然接近 0
    （窗口是按**参考自己的**分位带归零的）⇒ **「参考组平」不是任何证据**，
    **不得**写成「方法验证通过」。可说的是**留出组**与 **LUAD 组**的表现。
- **V3 不崩不空**：`cnv_fraction` 无 NA；`genomicScores` 窗口非空；基因账逐项记账。

### 15.4 参数（逐项显式；法则 3.1）

| 参数 | 取值 | 来源 |
|---|---|---|
| `prepareCounts` | **`FALSE`** | 🔴 **必须显式覆盖工具默认**，见下 |
| `aggregFactor` | `999` | 同上（`<1000` ⇒ 工具自己也拒绝聚合） |
| `referenceVar` / `referenceLabel` | 见 15.3 | 本臂 §11.2 / §12.1 口径 |
| `windowSize` / `windowStep` | `150` / `10` | 工具默认，**显式写出**（⚠️ 与 infercnv 的 101 **不同**） |
| `topNGenes` | `7000` | 工具默认，显式写出 |
| `thresholdPercentile` | `0.01` | 工具默认，显式写出 |
| `pooledReference` | `TRUE` | 工具默认；多切片汇池参考（＝ §11.2 借锚所需的机制） |
| `getCNVPerChromosomeArm` | `TRUE` | 逐臂产物，对应 §13.3 第 1 项的候选产物 |
| `getCNVClusters` / `doPlot` | `FALSE` / `FALSE` | 体检不做聚类与绘图，省时间；与 §13 关绘图同一理由 |

🔴 **为什么必须覆盖 `prepareCounts`**：其默认 `"default"` 在**切片 spot 数 < 60,000** 时
自动聚合，把同一群的相邻 spot 加总成 ~15,000 counts 的「meta spot」。
P4 上皮 spot **34,333 < 60,000** ⇒ **一跑就踩默认，逐 spot 分辨率被抹掉**。
本臂要的正是逐 spot 产物 ⇒ 必须关。

### 15.5 与 §3 infercnv 复现臂的关系：**不替换**

- §3.1「不引入 SpatialInferCNV 本体」与 §3.3 四个参数 **一字不改**。
- 本节**不**授权任何把 fastCNV 当作本臂引擎的用法。**换引擎不是换参数**，
  若日后要换，须**单独签字**并同时改写 §3.1「复现原文方法」这一前提。
- 本节只产出**事实**（快多少 / 自平性如何 / 用什么产物），供排期决策。

### 15.6 本节**不**改动的东西

§3、§3.1、§3.3、§11.2、§12.1、§13 全部、§14 全部、门 SC0–SC4 —— **一字不改**。

### 15.7 本节**不**声称

- 不声称 fastCNV 可用于本臂的恶性判定 —— 它的 `cnv_fraction` 是**连续分数**，
  其自带的 `CNVClassification` 用的是**它自己的默认阈值 ±0.1**，那是**工具默认、不是本臂口径**，
  ⚠️ 凡引用该阈值处**必须**注明来源（法则 3.2：不得把工具默认当本臂判据）。
- 不声称 fastCNV「更快」以外无代价 —— 已知代价**至少四条**，见 15.8。
- 不声称「参考组平」＝ 方法可信（见 15.3 的循环性声明）。
- ~~不声称本预印本方法已被同行评审。~~ 🔴 **此句已作废（2026-09-29）**：
  该文 2026-08-29 已在 **Genome Medicine** 正式发表（DOI `10.1186/s13073-026-01731-w`），
  **已同行评审**。原句基于 §15.2 的登记错误，见该处更正框。

### 15.8 本节附带登记的风险与缺陷（不在本臂判据内）

1. 🔴 **基因账不同**：fastCNV 只留 `protein_coding` ＋ `lncRNA` 且染色体 ∈ {1..22, X}，
   **chrY 与 chrM 被静默丢弃**，臂也按它自己**硬编码的着丝粒位置**切分。
   ⇒ 与本臂 §14.3 签的 `chr_exclude=c("chrM")`（chrX/chrY 保留）**不一致**，逐次记账。
2. 🔴 **多处参考（多标签）路径有静默错数**：`CNVCallingList` 的多标签分支里
   `SF[[i]] <- rowMeans(sapply(names(LN[[i]]), ...))` —— 若某标签**只出现在一张切片**，
   `sapply` 退化为**向量**而非矩阵，`rowMeans` 变成**跨基因的标量**，`rbind` 时被静默回收
   ⇒ **参考基线整条错掉且不报错**。
   ⇒ **本体检一律走单标签路径**（单标签分支是按切片 `sapply` 成矩阵，正确）。
3. ⚠️ `genes_by_arm` 的补齐循环遍历的是 `unique(geneMetadata2$chr_arm)`（只有 `"p"`/`"q"`），
   而 `names(genes_by_arm)` 是 `"1p"`/`"2q"` 这种 ⇒ 会凭空多出 `"p"`、`"q"` 两个各 200 基因的
   伪条目，混进选基因集（不建窗口，故不改变窗口结果，属浪费而非错判）。如实登记。
4. ⚠️ 默认 `CNVClassification` 阈值 `c(-0.1, 0, 0.1)` 是**工具默认**，本臂**未**签。
5. ⚠️ 本体检**未**覆盖多患者汇池（§11.2 借锚）—— 那一层须待借锚口径单独签字后再测。
6. 🔴 **多对象汇池路径实测崩溃**（本体检第一轮就撞上，非推测）：
   `CNVCallingList` 内部的 `funGenomicScore <- function(normcounts, GW)
   sapply(GW, function(g) colMeans(normcounts[g,]))` **缺长度 1 的保护**；
   而单对象版 `CNVCalling` 里同一处写法是
   `if (length(g) == 1) normCounts[g, ] else colMeans(normCounts[g, ])` —— **有保护**。
   窗口由 `topNGenes`（默认 7000）筛过后的基因建，某些**近端着丝粒短臂**
   （如 13p / 14p / 15p / 21p / 22p，其 p 臂本就近乎异染色质、基因极少）在 top-7000 里
   可能只剩 **1** 个基因 ⇒ `normcounts[g, ]` 退化为**向量** ⇒ `colMeans` 报
   `'x' must be an array of at least two dimensions` 而**硬崩**（实测报错原文）。
   ⇒ **本体检因此改用单对象路径**（`CNVCalling` ＋ `CNVPerChromosomeArm`），
   **不修改工具任何代码**；参考／观测的切分与汇池版**完全相同**。
   ⚠️ **这一条直接打在 §11.2 的借锚上**：借锚要的正是「多切片共用一个良性参考」，
   而**正是这条路径**有崩溃缺陷 ⇒ 借锚若日后要实现，须先解决/绕过此缺陷，
   并**单独签字**。本体检**未**测多患者汇池。

### 15.9 体检结果（2026-09-29 实测）

输入与 §15.0 的 infercnv 冒烟**逐字相同**：患者 P4，上皮 spot **34,333**
（Normal 8,587 ＋ AAH 7,988 ＋ AAH-1 7,131 ＋ LUAD 10,627），口径 `rctd_a` ＋ `argmax==上皮`。

**V1 速度**（判据：无门槛，只报数）

| 引擎 | 总墙钟 | 峰值内存 |
|---|---|---|
| fastCNV（单对象 `CNVCalling`） | **5.75 min**（读入建对象 2.15 ＋ 两次计算 3.44＝1.80＋1.63） | **18.58 GB** |
| infercnv（§15.0） | **990.24 min** | **46.04 GB** |

⇒ 墙钟约 **1/172**，峰值内存约 **1/2.5**。
🔴 快的原因**已登记在 §15.2**：它删掉了聚类 / 贝叶斯网 / HMM 三步（那三步占 infercnv 的 958 min）。
**不是**算法更强。⚠️ 另登记一处**我自己的记账更正**：首版 manifest 的 `elapsed_min_read`
实际写的是「到脚本结尾」的用时（位置放错了），已改为 `elapsed_min_load`（读入＋建对象）
＋ `elapsed_min_compute`（两次 `CNVCalling`），见 manifest 的 `v1` 字段。

**V2 自平性**（判据：只报分布与无阈值 AUC，**不设门槛**；🔴 循环性见 §15.3）

| 运行 | 参考集 | 切片（角色） | n | 中位 | [Q1, Q3] | 最大 |
|---|---|---|---|---|---|---|
| V2a | Normal＋AAH＋AAH-1 汇池 | Normal（参考） | 8,587 | 0.0093 | [0.0000, 0.0278] | 0.3611 |
| V2a | 同上 | AAH（参考） | 7,988 | 0.0093 | [0.0000, 0.0370] | 0.3426 |
| V2a | 同上 | AAH-1（参考） | 7,131 | 0.0046 | [0.0000, 0.0139] | 0.1898 |
| V2a | 同上 | **LUAD（观测）** | 10,627 | **0.5093** | [0.0278, 0.7361] | 0.9444 |
| V2b | **只用 Normal** | Normal（参考） | 8,587 | 0.0092 | [0.0000, 0.0275] | 0.3853 |
| V2b | 只用 Normal | **AAH（留出良性）** | 7,988 | **0.0138** | [0.0046, 0.0367] | 0.3394 |
| V2b | 只用 Normal | **AAH-1（留出良性）** | 7,131 | **0.0046** | [0.0000, 0.0138] | 0.2018 |
| V2b | 只用 Normal | **LUAD（观测）** | 10,627 | **0.5092** | [0.0321, 0.7294] | 0.9312 |

无阈值分离度（AUC ＝ P(LUAD 得分 > 对照得分)）：
- **V2a（🔴 循环，仅记录）：0.8469** —— LUAD 10,627 vs 良性参考 23,706
- **V2b（留出，承重）：0.8553** —— LUAD 10,627 vs **留出**良性 15,119

**可说的**（本次唯一不循环的观察）：把 AAH / AAH-1 从参考里**拿出来**之后，
它们**仍然判平**（中位 0.0138 / 0.0046，与作参考的 Normal 0.0092 同量级），而 LUAD 中位 0.5092。
⇒ 该工具的「平」不只是「参考自己被归零」的**构造后果**，在**没进参考的**良性切片上同样成立。

**不可说的**（逐条对应 §15.1 / §15.3 的禁令）：
- 这是**一个患者**（P4，4 张切片）的**逐 spot 打分**，**不是分类器性能**；
  spot 之间存在**空间自相关**，AUC 把 10,627 与 15,119 当成独立样本，**高估**其独立单位意义上的分离度。
- 分布是**双峰**不是平移：LUAD 的 Q1 只有 **0.028 / 0.032** ⇒ **至少 1/4 的 LUAD 上皮 spot 判平**；
  良性侧也有长尾（V2a 的良性 spot 最大到 0.34–0.36）。
- **不得**据此说「LUAD 有 CNV」：`cnv_fraction` 是「窗口值落在**参考自身 1–99% 分位带之外**的比例」，
  量的是**偏离参考表达谱**，**不是**基因组拷贝数（§15.1 已登记；铁律 2 的 CNV 证据要求未满足）。

**V3 不崩不空**：窗口 **216**；全 NaN 窗口 **0**；四张切片 `cnv_fraction` 的 NA 合计 **0**。
基因账：我方 symbol **18,082** − 未匹配 496 ＝ 进工具候选 **17,586**；chrY / chrM 由工具静默丢弃（§15.8 第 1 项）。

**产物**：`results/08_spatial_deconv/spatial_cnv/fastcnv_smoke_P4/`
（`fastcnv_smoke_P4_manifest.json` ＋ `fastcnv_smoke_P4_cnv_fraction.png`）；
日志 `logs/fastcnv_smoke_20260929/run.final.log`；脚本冻结 `logs/fastcnv_smoke_20260929/code_12_run_fastcnv_smoke.R`。

**本体检没有回答的**（不得被读成已回答）：
- **25 患者队列不可据此排期**：单患者；且借锚路径（§15.8 第 6 项）**实测有崩溃缺陷**，
  多患者汇池**未测**。
- **两引擎的分离度不可比**：infercnv 那份冒烟**没有**签过「逐 spot 判定取自哪个产物」
  （§13.3 第 1 项仍未签字）⇒ 只能比成本，**不能比好坏**。
- **换引擎仍需单独签字**（§15.5 一字不改）。

---

## 16. 🔏 签字记录六（2026-09-29）—— 外部对照锚 GSE248082（N1+N3）首次跑 RCTD

### 16.0 促成本次的事

用户 2026-09-29 问：「外部当时不是让你注册了外部对照数据集吗，是不是外部数据集的 RCTD 还没做」，
并裁定：**「签字：跑 N1+N3（细版参考 d）」**。

🔴 **如实登记**：该外部数据集此前**只存在于项目记忆与会话报告里，从未写进任何预注册文件**
（全库 grep `GSE248082` 在 `.md/.py/.R/.sh` 里**零命中**，只有 `data/external/GSE248082/` 的数据本身）。
本节是它的**首次落盘登记**，且**写在跑之前**。另：**全部四份 RCTD 产物**
（`rctd_a` / `rctd_a_thin100` / `rctd_a_thin50` / `rctd_d`）**都只有本队列 56 张切片**
（非 `GSM9226…` 打头的切片数 = 0）⇒ 外部切片**确实一张都没跑过**。

### 16.1 本节是什么，**不是**什么

- **是**：为 §11.2 / §14.6 里那 **15 个无自带良性切片的患者**准备**外部良性锚**的**第一步** ——
  在外部切片上跑出权重、挑出**上皮 spot**。
- ⛔ **不是** §11.2 的「借队列良性端」。§11.2 那条指的是借**本队列其他患者**的良性切片；
  本节是**跨研究、跨实验室的外部锚**，**属新口径**。
- 本次**不**产生任何**恶性判定**；**不**并进主队列 56 张；**不**改动任何既有口径。
- 本次**不**授权把外部锚用于全队列排期 —— 借锚口径**仍未签**（§14.6 一字不改）。

### 16.2 输入（逐字）

- **N1 = GSM8087031**、**N3 = GSM8087033**，路径 `data/external/GSE248082/`；
  文件为 `*_filtered_feature_bc_matrix.h5` ＋ `*_tissue_positions_list.csv.gz`
  （GEO 原始上传**不含** `matrix.mtx.gz`，也**不含** `spatial/` 子目录）。
- 平台 **10x Visium CytAssist FFPE**（GEO series matrix 逐字 `platform: 10x Visium Cytassist`）。
  探针集与本项目**逐行相同**：18,085 行 Gene Expression、**0 抗体行**，
  `features.tsv.gz` 前两列（ENSG＋symbol）sha256 前缀 `4c8ec5ddcf531b7ce0a564bbec0e25d5`
  **与我们的切片完全相同**（内容级核验，2026-09-25）⇒ `gene_order_spatial_hg38.tsv` 可复用。
- 🔴 **N2（GSM8087032）排除**：平均 **668 counts/spot**（N1 4,823 / N3 2,705），
  极浅，且深度正是让 RCTD 门控抖 **9.93%**（上皮集合 Jaccard 0.840）的那条轴。
- 🔴 **N4 / N5 排除**：`10x Visium`（3′ 冷冻）全套 **36,601** 基因，基因空间不同。
- ⇒ 可用外部锚**只有 2 张**。**n = 2 很薄，只能作辅助锚，不得当唯一锚。**

### 16.3 参数（逐项显式；法则 3.1）

**沿用项（与 `01_run_rctd.R` 逐项相同，一个都不改）**

- 参考：`results/08_spatial_deconv/reference_d.h5`（**细版 39 型**，与 §10.1 一致）；
  期望类型数取 `calibration.json` 的 `expect_n_types$d`。
- 🔴 **同时跑粗版 `reference_a.h5`（6 型）** —— 原因见下面的「登记更正」，**这一条是本节写完后、
  开跑前发现的**，不是事后加的参数。

🔴 **登记更正（2026-09-29，开跑前；我自己在选项文字里写错了）**

用户签的那条选项我写的是「用 `reference_d.h5` … 只为挑出外部良性上皮 spot」。
**这句在执行上不成立**：细版 d 的 39 型是 `AT1 / AT2 / Basal / Ciliated / Goblet_Mucous /
Serous / …`，**没有**「上皮」这个笼统类型名；而本臂**已签的**上皮门控口径是
**`argmax == 上皮`（§12）**，`上皮` **只存在于粗版 a**（6 型：
`上皮 / T_NK / 髓系 / 内皮 / 成纤维 / B_浆`）。
⇒ 只跑 d 挑不出上皮 spot。

**处置（不引入任何新口径）**：**a 与 d 两版都跑**（两版均已签字，§10.1），
- 上皮 spot 用**粗版 a 的 `argmax == 上皮`**（§12 已签，一字不改）；
- 细版 d 的权重作**配套产物**留档，**本次不给它定义任何上皮映射**
  （给 d 定义上皮 = 新口径，须单独签字；未签前**不得**用 d 挑锚）。
- ⚠️ d 的产物**不得**被读成「更精细的锚」。

> **教训（登记备查）**：选项文字里我写「用细版 d 挑上皮」，是把「用户要细版」与
> 「上皮门控只存在粗版」两件事混成了一句。口径的**用途**（挑上皮 spot）与用户选的
> **版本**（d）在这一点上不兼容，属我登记时未核对类型名所致。
- `doublet_mode="full"`、`UMI_min=100`、`counts_MIN=10`、`CELL_MIN_INSTANCE=25`、
  `UMI_max=2e7`、`UMI_min_sigma=300`、`MAX_MULTI_TYPES=4`、`CONFIDENCE_THRESHOLD=5`、
  `DOUBLET_THRESHOLD=20`、`gene_cutoff=0.000125`、`fc_cutoff=0.5`、
  `gene_cutoff_reg=0.0002`、`fc_cutoff_reg=0.75`、`n_max_cells=10000`、`min_UMI=100`、
  `require_int=TRUE`、`max_cores=4`、`seed=1`。
- `calibration.json` 的 `signed` 必须为 `TRUE`（未签硬停），并校验 `n_max_cells` 一致。

**新增项（外部切片专用，必须显式登记）**

| 项 | 取值 | 理由 |
|---|---|---|
| 计数来源 | **h5**（`matrix/{data,indices,indptr,shape,barcodes,features}`） | GEO 包无 `matrix.mtx.gz` |
| 坐标来源 | **扁平** `*_tissue_positions_list.csv.gz`（**带表头**） | GEO 包无 `spatial/` 子目录 |
| spot 掩码 | **同规则现算**：`nUMI<500` 或 `nFeature<200` 或 `pct_mt>15%` ⇒ 剔（OR） | 套用 SP §3.3 已签阈值；外部切片不在冻结掩码里 |
| `MT-` 前缀 | `MT-`（同 `00_spatial_qc.py`） | 指标定义一致 |
| 双探针 symbol | 按 symbol 求和取一次（同 `01_run_rctd.R`） | 探针集相同 |
| **G1 基因交集硬门** | 🔴 **放宽为「只报告」**，**不硬停** | 见下 |

🔴 **为什么 G1 在外部切片上必须放宽**：`GENE_INTERSECTION_EXPECTED = 18066` 是
**本队列切片 vs 参考**的实测值（RCTD_PREREG §2.1）。外部切片与参考是两个互不包含的基因宇宙，
交集数**必然不等于** 18,066 ⇒ 硬停就等于「因为口径错配而拒绝执行已签的事」。
⇒ 本次**只报告**交集数（参考有切片无 / 切片有参考无 各多少），**并如实写进报告**。
**这是放宽，不是等价替换。**

### 16.4 判据（执行前定）

- **R1** 两张切片都产出权重（无硬停）；
- **R2** 权重非负（G2 保持）；
- **R3** 逐切片、**逐 caliber** 报告：QC 后 spot 数、N0、进 RCTD 的 spot 数；
  粗版另报 `argmax == 上皮` 的 spot 数及占比（细版**不**报上皮数，见 §16.3 登记更正）；
- **R4** 报告 `in_tissue == 1` 的 spot 数是否 ≡ filtered barcodes（本项目 SP0 的那条一致性，
  在外部切片上**首次核对**）。

**判据只报，不设门槛。** 本步**不判**外部锚可用与否。

### 16.5 本记录**不**声称

- **不**声称外部锚可用 —— 「外部锚自身 CNV 是否平」的体检**尚未做**（下一步，须单独定工具与判据）。
- **不**声称外部切片的谱系注释可信度与本队列相同（不同实验室、不同患者、批次效应未评估）。
- **不**声称 `n = 2` 能支撑任何结论；**不**声称 N2 的排除阈值有外部依据。
- **不**解除任何禁令；`argmax == 上皮` 仍是唯一门控口径，`argmax` 仍**不是**恶性判定（§12 不变）。
- **不**改 §3、§11.2、§13、§14、§15 一个字。

### 16.6 本节附带登记的缺陷与风险

1. 🔴 **外部切片没有冻结掩码**（同规则**现算**）⇒ 与本队列**不是同一条产线**，报告须标明。
2. 🔴 **G1 硬门在外部切片上被放宽为「只报告」**（理由见 16.3），属**放宽**。
3. ⚠️ **n = 2**；N2 因深度被排除，而该深度阈值（668 vs 4,823）**无外部依据**，是本项目自定的。
4. ⚠️ 外部切片的 `in_tissue` / 坐标出自 GEO 原始上传，**未**与本项目 SP0 那条
   （`in_tissue==1 ≡ filtered barcodes`）对过 —— 本次**首次核对**（R4）。
5. ⚠️ **尚未做**「外部锚自身 CNV 是否平」的体检；**不平则该锚作废**。
6. ⚠️ 本步只挑上皮 spot，**不**判定这些 spot 是良性 —— 外部切片标注为"Normal human lung"，
   但那是**供体的临床标签**，不是逐 spot 的病理判定。

### 16.7 下一步（**不在**本次授权内）

- **外部锚自身平不平**的体检（工具与判据**须单独签字**）；
- **§11.2 / §14.6 借锚口径**签字（**仍未签**）—— 签之前不得实现、不得排全队列。

---

## 17. 🔏 签字记录七（2026-09-29）—— 借锚池并列、本轮只跑自带锚 10 例、外部锚体检规格

> **本节的效力高于 §3.4 正文里「三个候选处置」那一段，也高于 §16.7 的「下一步」那一段。**
> 出处：用户 2026-09-29 裁定（三个选项）；由 Claude 按其选项代笔落盘，
> **未代其决定任何未答复项**。

### 17.0 促成本次的事

用户在看完外部 H&E 质量图后问：「只有这两张切片是和我们相同技术的，你觉得三张正常切片
够我们去铆钉全队列 cnv 吗」。Claude 的回答是**不够**，并说明了四条理由（见 17.1 的事实），
最后把三个**属于用户**的问题摆出来。用户答：①借锚池 **两者并列都跑**；
②借锚臂判定权限 **先只跑 10 个自带锚患者**；③外部锚体检 **要：用已签的 fastCNV 比**。

### 17.1 本轮核实的事实（**逐条实测/查证，非推测**）

| # | 事实 | 来源 |
| :-- | :--- | :--- |
| 1 | 队列共 **56 张切片 / 25 患者**：「自带良性锚」的患者 **10 例** = P1 P2 P4 P6 P9 P11 P20 P22 P24 P25 | `results/08_spatial_deconv/rctd_a/per_slide/` 逐文件名核对 |
| 2 | 上述 10 例的良性切片**除 P4 是 Normal 外，其余 9 例全是 AAH** | 同上 |
| 3 | **缺**自带良性锚的患者 **15 例** = P3 P5 P7 P8 P10 P12 P13 P14 P15 P16 P17 P18 P19 P21 P23（多为 AIS+MIA/LUAD 配对） | 同上 |
| 4 | **全部 25 患者**在本队列 GEO characteristics 里都有 age / sex / smoking | 本队列 GSE307534 的 GEO 系列元数据（本轮逐患者读过） |
| 5 | 外部 N1/N3 的 GEO 元数据里**没有** sex / donor 字段 ⇒ **无法判断 N1 与 N3 是否同一供体** | GSE248082 SOFT |
| 6 | 性别构成：自带锚的 10 例 = ~~6 女 / 4 男~~ 🔴 **实为 5 女 / 5 男**（女 = P1 P4 P9 P11 P22；男 = P2 P6 P20 P24 P25）；缺锚的 15 例 = **7 女 / 8 男**（复核为**正确**） ⇒ **同性别配对在队列内做得到** | 事实 4 的元数据逐患者统计；🔴 **2026-09-29 更正见 §19.3**（GEO 系列元数据重取核对） |
| 7 | §14.3 已签 `chr_exclude = c("chrM")` ⇒ **chrX/chrY 留在信号里**；§14.6 已登记「借锚一旦实现，性别混淆才真正被引入」 ⇒ **同性别配对**正好在不重新签 §14.3 的前提下关掉这个混淆 | §14.3 / §14.6 |
| 8 | 外部 N1/N3 是**标准 6.5 mm 框**；本队列是 **11×11 mm 框**；**探针集相同**（18,085 个 Gene Expression 行） | 本会话 GEO 元数据 + 逐文件核对 |
| 9 | 借锚路径**仍未实现**：`11_run_spatial_cnv_smoke.R` 在 `n_ref == 0` 处 `stop()` ⇒ 现在**只有**自带锚的 10 例跑得动 | §14.6 第 1 项 |

**由事实 1–9 推出的结论（回答用户的问题）**：三张正常切片**不足以**"铆钉全队列 CNV"，
理由是**四条中的任何一条都独立成立**：①不是同一批个体（§3.4 已登记失败模式）；
②供体数不明且可能不独立（事实 5）；③外部与我们是不同框、不同批次，而本臂**已实测**
对深度敏感（计数减半 ⇒ `argmax` 移动 9.93%、门控翻转 8.30%）；
④**体检尚未做**（事实：§16.6 第 5 项）。
🔴 **承重后果**：锚若偏弱会**制造**恶性标签 —— 在**铁律 2** 下，这比"判不了"更坏。
⇒ 外部锚**救不了**缺锚的 15 例，它只能把"无判定"变成"依赖锚的判定"。

### 17.2 裁定一：借锚池 = **两者并列都跑**

| 池 | 内容 | 角色 |
| :--- | :--- | :--- |
| **池 A（队列内，同性别配对）** | 缺锚患者的**同性别**自带锚供体的良性上皮 spot | 主锚候选 |
| **池 B（外部 GSE248082）** | N1 + N3 的正常肺上皮 spot | 并列候选，**不预设优先级** |

- **两者并列**：不做「先用池 A、不够再用池 B」的级联 —— 那会引入择优顺序。
- 逐患者**标明**该锚来自哪一池（沿用 §11.2「借来的锚须逐患者标注」）。
- ⚠️ 池 A 的可行性**依赖事实 6**；若某患者找不到同性别供体，该患者记 **NOT RUN**，
  **不得**退回异性别（那会重开 §14.6 的性别混淆）。

### 17.3 裁定二：**本轮只跑 10 个自带锚患者**（借锚臂**不实现**）

- 本轮**不**实现 §14.6 第 1 项的借锚路径、**不**碰池 A / 池 B 的落盘实现。
- 先看自带锚 10 例的 SC2–SC4 结果，**再**决定借锚臂是否值得签。
- ⇒ 缺锚的 15 例本轮一律记 **NOT RUN（未被判定，不是阴性）**。
- 依据：§17.1 事实 9 + 「先把 RCTD 收尾和外部锚体检做完，这两条我下面提给你签」。

### 17.4 裁定三：外部锚体检 = **用已签的 fastCNV 比**

- **用 §15 已签的 fastCNV**（1.1.11）做，**不改 §15.4 任何参数**；
  仍走**单对象 `CNVCalling`** 路径（§15.8 第 6 项：汇池路径实测崩溃）。
- **§15.2 的出处标注**：~~`bioRxiv 2025.10.22.683855`，**预印本、未经同行评审**~~
  🔴 **已更正（2026-09-29）**：正刊 = **Genome Medicine**，DOI `10.1186/s13073-026-01731-w`，
  2026-08-29 上线，**已同行评审**。体检仍用 **fastCNV v1.1.11**、参数不变。
- 本体检**只回答「外部锚自己平不平」**，**不产生**任何恶性判定，**不进** SC0–SC4。

### 17.5 外部锚体检**执行前规格**（判据 F1–F4；**阈值由 Claude 起草、可撤回**）

**运行 A（跨队列）**

- **参考**：`argmax == 上皮`（§12.1）的上皮 spot，**汇池自除 P4 外的 9 例自带锚患者**
  （P1 P2 P6 P9 P11 P20 P22 P24 P25）的良性切片。
  🔴 **登记在案的警告**：这 9 张**全是 AAH**（事实 2）⇒ 参考是**AAH 上皮**，不是组织学正常上皮；
  P4 是唯一有 Normal 切片者，**被留出**。本警告使得 F2 是**保守**自检。
- **观测**：① P4_Normal 上皮 ② P4_AAH + P4_AAH-1 上皮 ③ **P4_LUAD 上皮（阳性对照）**
  ④ N1 上皮 ⑤ N3 上皮。
- **统计量**：逐 spot `cnv_fraction`（fastCNV 原生列）。
- 🔴 **循环性声明（承 §15.3）**：参考组自己的 `cnv_fraction` 由构造必然 ≈ 0
  ⇒ **参考组平不是证据**；承重的是**观测组**的数。

**判据**

| # | 判据 | 阈值 | 越界后 |
| :-- | :--- | :--- | :--- |
| **F1** | 阳性对照必须响：`median(P4_LUAD)` 与 `AUC(P4_LUAD vs 参考)` | ≥ 0.10 且 ≥ 0.75 | **体检作废**（无分辨力）⇒ 对 N1/N3 **什么都不能说** |
| **F2** | 同队列良性必须平：`median(P4_Normal)` / `median(P4_AAH)` / `median(P4_AAH-1)` | 各自 ≤ 0.05 | **体检作废**；🔴 **不得**读成「外部锚不平」（是本检验自己没分辨力） |
| **F3** | 外部必须平：`median(N1)` / `median(N3)` | 各自 ≤ 0.05 | 外部锚**不得**当主锚（可仍作对照臂）；**须**用运行 B 判是否批次所致 |
| **F4** | 批次解耦（**Claude 追加，可撤回**）：参考 = N1 上皮 ⇒ 观测 N3 上皮（及其反向） | `median` ≤ 0.05 | 运行 B **不平** ⇒ 外部**内部就有结构**；本设计仍**不能**把它判成恶性（无 ground truth），**只能报「内部不平」** |

**阈值出处（诚实标注，均可在签字时推翻）**

- `0.05` ≈ §15.9 实测良性上限（0.0046–0.0138）的 **4 倍**；
- `0.65` **未被**用作阈值（§15.9 那条「弱信号线」保留在别处，本体检不引）；
- `0.75` = 「明显分得开」；
- `0.10` ≈ §15.9 实测 LUAD 中位 0.5092 的 **1/5**。

**失效规则（一并登记，避免事后解释）**

1. **F1 不过 ⇒ 全盘作废**，不得只报 F2/F3；
2. **F2 不过 ⇒ 全盘作废**（本检验对"同队列良性"都没分辨力，谈外部无意义）；
3. **F3 不过而 F4 平** ⇒ 更可能是**批次**；**F3 不过且 F4 也不平** ⇒ 「外部内部不平」，
   但**仍不得**称其恶性；
4. 🔴 **本设计分不开「不平」与「批次效应」** —— 这是**已登记的局限**，
   运行 B 只**缩小**不解**除**这个不确定。

**参考的抽稀（执行前定，非事后调整；Claude 起草，可撤回）**

- 每张参考切片的上皮 spot **最多取 2,000 个**（`set.seed(1)` 后按 barcode 排序抽样；
  抽中的名单**落盘备查**）。9 张 ⇒ 参考 **≤ 18,000** spot。
- **观测组不抽稀**（判定对象是全量）。
- 理由：①本机**背景病理进程在跑**，全量对象按 §15.9 实测外推约 **50 GB**，
  抽稀后约 **32 GB**；②逐切片等量可避免「深切片主导参考基线」
  （实测 P6 8,718 vs P25 1,963，差 4.4 倍）。

**§17.5 附：进本体检的 spot 数（2026-09-29 实测，`argmax == 上皮` 同 §12.1）**

| 组 | 切片 | 上皮 spot |
| :--- | :--- | ---: |
| 参考 | P1_AAH 4,745 / P2_AAH 6,514 / P6_AAH 8,718 / P9_AAH 6,514 / P11_AAH 8,314 / P20_AAH 7,046 / P22_AAH 5,454 / P24_AAH 4,131 / P25_AAH 1,963 | **53,399** |
| 观测① | P4_Normal | 8,587 |
| 观测② | P4_AAH 7,988 + P4_AAH-1 7,131 | 15,119 |
| 观测③ | P4_LUAD（阳性对照） | 10,627 |
| 观测④ | N1 | 3,822 |
| 观测⑤ | N3 | 尚未产出（RCTD 在跑） |

- ⚠️ **N3 的 QC 剔除率 13.50%**（N1 只有 1.36%）—— 458 个 spot `nUMI<500`、
  204 个 `nFeature<200`、20 个 `pct_mt>15%`。这使 N3 是本体检里**最浅**的一张，
  其 `cnv_fraction` 的噪声**天然更大**；判 F3 时须一并报出（**不**因此调阈值）。

### 17.6 🔴 新发现的阻塞（**登记，未处置**）：`analysis_mode="samples"` 下**没有**逐 spot 产物

本条是 §13.3 **第 1 项**的正面回答，出自**读既有 P4 冒烟产物**（未重跑）：
`results/08_spatial_deconv/spatial_cnv/smoke_P4/infercnv_out_P4/`。

**实测**：`17_HMM_predHMMi6.hmm_mode-samples.cell_groupings` 的 `cell_group_name` 列
**只有 2 个取值** —— `C_benign_epi.C_benign_epi_s1`（23,706 参考 spot）
与 `obs_P4.obs_P4_s1`（**10,627 张 P4_LUAD 的 spot 全部归为同一个组**）。
`*.pred_cnv_regions.dat` 全文 908 B、15 行，`cell_group_name` **只有 `obs_P4.obs_P4_s1`**。

⇒ **`analysis_mode="samples"` 的 HMM 输出是"每张切片一组"，不是"每个 spot 一个状态"。**
对照：同一批数据在 `hmm_mode-subclusters` 下 `cell_groupings` 有 **246** 个组。

**两个独立原因使 SC4 在当前已签设定下**取不到**逐 spot 产物**：

1. §13.1 已签 `analysis_mode = "samples"` ⇒ HMM 是**切片级**；
2. `11_run_spatial_cnv_smoke.R` 第 329 行 `write_expr_matrix = FALSE`
   ⇒ infercnv 的**逐细胞残差矩阵**（`infercnv.observations.txt`；1.23.0 实测会写，
   见 `results/03_cnv/infercnv_smoke/infercnv_out/`）**没有落盘**。

🔴 **由此 §13.5 那句「逐 spot 判定来自 HMM 那一步」在已签设定下不成立** —— 登记为缺陷。
**本项未处置**；处置须用户签字（**要改的是什么，见本节末的待签项**）。

### 17.7 本节**不**声称

- **不**声称外部锚可用或不可用 —— 体检**尚未跑**；
- **不**声称三张正常切片（N1/N3 + 其它）能当主锚；
- **不**声称池 A（同性别配对）一定覆盖得了缺锚的 15 例；
- **不**声称 §17.5 的阈值有外部依据（**Claude 起草，可撤回**）；
- **不**改 §3 / §11.2 / §12 / §13 / §14 / §15 / §16 一个字。

### 17.8 本节**不**改动的东西

- §13.3 第 2 项（SC2 第一炮必须单患者）**一字不改**；
- §12.1 的 `argmax == 上皮` **一字不改**；`argmax` 仍**不是**恶性判定；
- 铁律 2 / 铁律 5 / 铁律 6、「恶性×权重」禁令、§11.2 的 C 主 + D 对照设计 **均不改**；
- §16.7 的两条"下一步"**仍然未签**（本节只**追加**规格，不代签）。

### 17.9 本节登记后**仍待签**的两项（承 §13.3）

| # | 待签项 | 备选（**均未经用户选择**） |
| :-- | :--- | :--- |
| **1** | 逐 spot 判定取自哪个产物（§17.6 已证明**当前设定下不存在**） | ① 改签 `analysis_mode="cells"`（成本未测，按单位数外推约 3×10¹ h 量级 ⇒ 疑不可行）；② 保持 `samples` + 改 `write_expr_matrix=TRUE`，**由本臂自算**逐 spot 统计量（须登记为"本臂的统计量"，非 infercnv 的 HMM 判定）；③ 声明本臂**做不出**逐 spot 判定，把 SC4 单位降级（与 §6 冲突，须单独签） |
| **2** | SC2 第一炮 = **单患者** | 无备选；照 §13.3 第 2 项执行 |

---

## 18. 🔏 签字记录八（2026-09-29）—— **换引擎**：本臂引擎由 infercnv 复现臂改为 fastCNV

### 18.0 促成本次的事

用户指示（逐字）：

> 「fastcnv 是 nature 的文章吧，这个只是有预印本而已啊，你去查查**如果来自正刊就全面升级替代**。」

**条件已核实为真**（Crossref 逐字段，见 §15.2 更正框）：
fastCNV 已于 **2026-08-29** 在 **Genome Medicine**（ISSN 1756-994X，
DOI `10.1186/s13073-026-01731-w`）**正式发表、已同行评审**。
⇒ 用户的条件成立，本节据其指示执行「全面升级替代」。

⚠️ 须如实说清的两点：
1. 是 **Genome Medicine**（Springer Nature / BMC 旗下），**不是 Nature 品牌刊**；
2. 「正刊」只消掉了 §15 当初列的四条代价里的**一条**（出处未评审），
   另三条（§15.8 第 1/2/4 项）**原样存在**，见 §18.4。

### 18.1 裁定一：本臂引擎 = **fastCNV v1.1.11**

- 本臂（空转 CNV 臂）的**逐 spot 恶性判定引擎**改为 **fastCNV v1.1.11**
  （`R_LIBS=/home/eto/Rlibs/fastcnv`，GPL-3，入口 `CNVCalling` ＋ `CNVPerChromosomeArm`）。
- **infercnv 复现臂 RETIRED**：§3 的 infercnv 实现线**不再执行**，其已跑产物
  （`results/08_spatial_deconv/spatial_cnv/smoke_P4/infercnv_out_P4*`）
  **留档为历史记录**，**不得**再作为本臂判定的输入。
- §15.4 已签的参数（`prepareCounts=FALSE`、`windowSize=150`、`windowStep=10`、
  `topNGenes=7000`、`thresholdPercentile=0.01`、`getCNVPerChromosomeArm=TRUE`）
  **沿用**（它们本就是 fastCNV 的参数）。
- 参考／观测切分沿用 §11.2（C 主 ＋ D 对照）与 §12.1（`argmax == 上皮`）。

### 18.2 裁定二：§3.1「复现原文方法」这一前提**作废**，改写如下

§3 标题与 §3.1 的原文（「用 `infercnv` 实现原文记录的 SpatialInferCNV 流程」
「本臂产出的应描述为『**原文方法的复现**』」）**整段作废**，改写为：

> **本臂是一个独立实现**：在 **fastCNV**（Genome Medicine 2026，
> DOI `10.1186/s13073-026-01731-w`）之上做**逐 spot 恶性判定**。
> 它**不是**原文 `SpatialInferCNV` 的复现，**也不是**原文代码的运行。
> 报告里**不得**写「复现了原文方法」，**不得**写「用了 SpatialInferCNV」，
> **须**写「本臂引擎 = fastCNV v1.1.11（已发表工具），非原文流程的复现」。

⚠️ **这是本臂对项目目标的一次实质降级，必须如实登记**：
源论文（Peng 2026 Cancer Cell）的 CNV 臂我们是**复现不了**了。
用户 2026-09-24 的裁定「全项目唯一的恶性判定来源 = 空转 CNV」
**仍然成立**，但该判定**不再可声称与原文同法**。

### 18.3 这次替换**顺带解决**的问题（**不是**新裁定，是后果）

1. 🔴 **§17.6 的阻塞消失**：fastCNV 原生产出**逐 spot `cnv_fraction`**
   ⇒ 不再依赖 infercnv 的 HMM 分组。**§17.6 整条作废（问题不存在了）。**
2. **§13.3 第 1 项的三个备选（①`cells`／②`write_expr_matrix=TRUE` 自算／③降级 SC4）
   全部作废** —— 它们都是「infercnv 取不到逐 spot 产物」的补救，**问题本身没有了**。
3. **§13 整节作废**（`analysis_mode` 是 infercnv 专属概念，fastCNV 无此项）。
   但 §13.3 第 2 项（**SC2 第一炮必须单患者**）**保留**，理由不变。
4. **队列可行性翻转**：infercnv P4 实测 **990.24 min**（§15.0）对 fastCNV **5.75 min**（§15.9）
   ⇒ 56 张全队列由「按单患者 16 h 外推需数周」变为**约数小时量级**。
   这正是「替代」的真正收益，且**与它是不是正刊无关**（§15.9 早已测出）。

### 18.4 换引擎**没有**解决的问题（逐条登记；**均须重新裁定**）

| # | 问题 | 出处 | 现状 |
| :-- | :--- | :--- | :--- |
| 1 | fastCNV **硬编码丢掉 chrY 与 chrM**（`chromosome_name %in% c(1:22,"X")`），而 §14.3 签的是 `chr_exclude=c("chrM")`（**chrX/chrY 保留**） | §15.8 第 1 项（源码级核验，2026-09-29 复核**仍成立**） | 🔴 **未裁定**：§14.3 与 §14.6 的性别混淆论证都要重判，见 §18.5(b) |
| 2 | 多标签参考路径有**静默错数**（`sapply` 退化） | §15.8 第 2 项 | ⇒ **必须走单标签路径**，否则参考基线整条错掉 |
| 3 | 多对象汇池路径**实测硬崩** | §15.8 第 6 项 | 🔴 **直接打在借锚上**：借锚要的正是多切片共用参考，而即这条路崩 |
| 4 | 判定阈值未签（工具默认 `CNVClassification(peaks=c(-0.1,0,0.1))` 是**工具默认**） | §15.8 第 4 项 | 🔴 **未裁定**，见 §18.5(a) |

🔴 **第 1 项的一个反直觉细节（须一并登记）**：fastCNV 丢 chrY 会**顺带消掉**
§14.6 里「借异性别锚 ⇒ chrY 剂量假信号」那**一条**混淆；
但 **chrX 仍在信号里** ⇒ 借异性别锚的 chrX 剂量混淆**依然存在**
⇒ **§14.6 的同性别配对理由仍然成立**（只是少了一半）。
**不得**把「工具丢了 chrY」写成「性别混淆问题解决了」。

### 18.5 三项子裁定（**(a)(b) 已签 2026-09-29；(c) 见 §18.9 仍待签**）

**(a) ✅ 已签：恶性判定口径 —— `cnv_fraction` 的阈值**

- `cnv_fraction` ∈ [0,1] = 非零窗口占比。**它越高越像 CNV，但工具不提供恶性判定**
  （`CNVClassification` 的 `peaks` 是**方向**分类 `del/neutral/amp`，**不是**恶性与否）。
  ⇒ 阈值**必须我们自己签**，这正是 §15.8 第 4 项留的口子。
- 🔏 **生效口径**：
  - **主阈值 = `0.05`** —— 锚在**我们自己实测的**良性上限上（§15.9：良性 **0.0046–0.0138**、
    LUAD 中位 **0.5092**），取良性上限的 ~4 倍。**不用工具默认。**
  - **敏感性档位 = `0.02 / 0.05 / 0.10 / 0.15`**，**逐档全报**；
  - **不按阈值筛选 spot**（spot 一律留在上报里，阈值只决定标记）
    —— 沿用 RCTD margin 那套「口径不动 ＋ 敏感性复核」的处理方式。
- ⚠️ 该 0.05 与 §17.5 的 `TH_FLAT_MEDIAN` **恰好同值**，但两者是**两件事**
  （一个是「锚平不平」，一个是「spot 恶不恶」），**不得混用**。

**(b) ✅ 已签：chrY/chrM 缺失并入 §14.3** → 取**改签**方案：

- §14.3 有效口径改为「**常染色体 ＋ chrX；chrY 与 chrM 排除**」，
  §14.6 的性别守卫**收窄为只针对 chrX**。**两项均已落笔**（见 §14.3 二次改签框、§14.6 收窄框）。
- ⚠️ **同性别配对的理由仍然成立**（chrX 剂量差照样造假信号），只是少了一半。

**(c) 🕐 门 SC0–SC4 重写 —— 见 §18.9，仍待签**

### 18.6 本节**不**声称

- **不**声称 fastCNV「更好」—— 它快是因为少了聚类／贝叶斯网／HMM（§15.2），
  **不是**算法更强；**不得**暗示「升级到更好的方法」。
- **不**声称换引擎后本臂结论与原文可比 —— 恰恰相反（§18.2）。
- **不**声称 §18.5 的三个 (a)(b)(c) 已签 —— 它们**全部未签**。
- **不**声称 §15.9 的体检结论因「正刊」而改变 —— 体检测的是速度与自平性，与出处无关。

### 18.7 本节**不**改动的东西

- §11.2（C 主 ＋ D 对照）、§12.1（`argmax == 上皮`）**一字不改**；
- 铁律 2 / 铁律 5 / 铁律 6、「恶性×权重」禁令 **均不改**；
- §14.3 / §14.6 **暂不改**（改法待 §18.5(b) 签字）；
- §16（外部锚 RCTD）、§17 的裁定一/二/三（借锚池并列、只跑 10 例、外部锚体检用 fastCNV）
  **均不改** —— §17.4 本就是「用已签的 fastCNV 比」，与换引擎**同向**；
- §13.3 第 2 项（SC2 第一炮单患者）**保留**。

### 18.8 附注：已启动的体检（**未因换引擎而作废**）

外部锚体检 `16_run_fastcnv_anchor_flatness.R`（§17.5）**已于 2026-09-29 19:48 启动**
（真 PID 1331951，PPID=1，`logs/fastcnv_flatness_20260929/run.log`）。
它测的是**外部锚自己平不平**，与本节换引擎**同向**（§17.4 本就是「用已签的 fastCNV 比」）
⇒ **不停止**。
⚠️ 该脚本**启动时**日志头部仍有一句旧出处「**预印本，未经同行评审**」——
脚本源码已于启动后**当场改掉**（第 133 行、第 420 行），但**已运行的进程已解析完源码**，
⇒ **本次运行的日志头部那句话是旧的、错的**，以 §15.2 更正框为准。这与 §17.6 一样属
「已跑的产物里留了一句错话」的登记，**不得**据它引用。

🔴 **首次启动即崩（Claude 自己的 bug，代码级，已修，2026-09-29）**：
`Error: !any(use == 0L) is not TRUE`，在第 212 行、**第一张切片**就硬停。
**根因**：`Matrix::readMM()` 读 `.mtx` **不设 dimnames**（mtx 格式里根本没有行列名），
而我却拿 `colnames(m)` 去做 barcode 匹配 ⇒ colnames 是 `NULL` ⇒ **逐张全 0 匹配**。
**对照证据**：能跑通的冒烟脚本 `12_run_fastcnv_smoke.R` 第 137 行匹配的是
**`bc` 向量**（`match(epi_bc[[s]], bc, nomatch=0L)`）并把 `bt <- bc[use]` 单独带着走，
**从不依赖 `colnames(m)`** ⇒ **是我在改写时偏离了模板的写法**，非工具问题。
**修法**：在 mtx 分支显式补 `colnames(m) <- bc`（h5 分支 `read_h5_counts` 本来就设了）。
⇒ 这条与 §13.3「冒烟逮到的 bug」同类，**登记在案**（未产生任何结果，无需作废任何数）。

🔴 **第二次崩（Claude 自己的 bug，代码级，已修）**：`getv()` 把元数据列名写死成 `o$g_a`，
而运行 B 的对象那列叫 `g_B` ⇒ `'g_a' not found in this Seurat object; Did you mean "g_B"?`。
**代价**：运行 A 的结果只存在内存里、清单在最后才写 ⇒ **A 白跑一次**（约 10 分钟）。
**修法**：`getv()` 加 `grp_col` 参数，调用处传 `"g_B"`；
**并加两条防呆**：运行 A / 运行 B 的逐 spot 分数**各自立刻 `saveRDS` 落盘**
（`runA_spot_scores.rds` / `runB_spot_scores.rds`）⇒ 后面再崩也不用重算 A。

🔴 **第三次崩（Claude 自己的 bug，日志级，已修）**：`Error in sprintf(...):
required resulting string length 888629 is greater than maximal 8192`，
`In addition: likely truncation of character string to 8191 characters`，
崩在「运行 A 逐切片 cnv_fraction」那段**纯日志**打印上（`Calls: step -> cat -> sprintf`）。
**根因已定位（2026-09-29，实据，不是推测）**：⚠️ 我第一次写的「根因未定论」**作废**。
`getv()` 里的 `o[[grp_col]]` 取回来的**不是向量，而是一个单列 `data.frame`**
⇒ `as.character()` 把**整列**deparse 成**一个**长字符串
（内容形如 `c("cohort_benign_epi", "cohort_benign_epi", …)`），
长度 1 又被 `data.frame()` **静默循环**贴到全部 57,167 个 spot 上。
**实据**（从落盘的 `runA_spot_scores.rds` 量出来的）：
`nchar(tab_a$group)` = **888629 × 15 行全同**，`substr` 打头就是 `c("cohort_benign_epi", …`、
结尾是 `…"obs_other")`；`va$grp` 是 `character`、`length=57167`、**每个元素都是那个 888,629 字的巨串**。
这个巨串进了 `sprintf("%-18s", …)` ⇒ R 报 `required resulting string length 888629`。
**为什么只有这一处炸**：`slide` 走的是 `o$slide`（`$` 分派）⇒ 是正常向量；
只有走 `[[` 的 `grp` 中了招。⇒ 与工具、与数据**都无关**，是我自己的一个取数写法。
**修法**：① 改直接读 `o@meta.data`，绕开 `[[` 分派；② 加**长度守卫**
（三列长度必须 == `ncol(o)`）＋ **超长串守卫**（`nchar(grp) > 100` 即硬停，拒绝静默）；
③ `collect()` 里分组名一律 `paste(..., collapse="|")`，**保证长度 1**；
④ 判据里 `if (F1)` 改 `if (isTRUE(F1))`（`F1` 为 `NA` 时原来会崩在 `if`）。
⚠️ 出错那次 `sprintf` 的位置我**报错过**：我说「逐项拆测都没能复现」——
其实那个报错只在**「8 个实参 + `%-18s` 宽度」这个组合**下出现，松掉任一条就不再触发，
所以按元素拆着试当然复现不了。**登记为我自己的又一次误判**。
**修法（两条，均为工程加固、**不改任何判据**）**：
1. `step()` 整体包 `tryCatch` ⇒ 格式化失败**降级成一行 `[LOG-ERROR] fmt nchar=… nargs=…`**，
   **绝不允许日志把 30 分钟的计算打死**；下次真出问题时那行会把 `fmt` 长度直接报出来。
2. 逐 spot 分数立刻落盘（同上）。
⇒ 三次崩**全部是 Claude 自己的代码 bug、全部在代码级修掉**，
**未产生任何科学结果、无需作废任何数**；外部锚**平不平**这件事至今**一次都没测出来**。

🔴 **门脚本 `17_run_fastcnv_sc_gates.R` 首跑的 SC0② 假报警（Claude 自己的 bug，已修）**：
首跑结论 `FAIL（未过：SC0② GE 行数 / SC0② 抗体行）`，**两条都是我的期望值写错**：
① 我把「每张切片都有 35 行抗体」当成通用事实（实为 **45/56 有 35 行、11/56 为 0**，见 §2.1 更正框）；
② 更隐蔽的一条：`sc0_ge` 数的是 **`nrow(ft_all)` 总行数**，不是 `Gene Expression` 行数
⇒ 那 45 张总行数 18,120 ≠ 18,085，**全判错**（改为 `sum(ft_all$type == "Gene Expression")`）。
**同时补了一条门**：除 `Gene Expression` 与 `Antibody Capture` 外**不得有第三类 feature**。
⇒ **数据、工具、口径都没问题**；同一跑里 **SC2 是过的**（见下），门不过纯属我的常数写错。

🟢 **同次首跑的 SC2 结果（有效，但**分量很轻**）**：同一参考（23,706 spot）同一输入重复 3 次，
**34,333 个 spot 的 `cnv_fraction` 逐位完全相同（1.000000，门槛 0.95）**，锚名单逐字节相同。
🔴 **必须声明它的局限**：`CNVCalling` 在给定参考下是**确定性的** ⇒ 这个门**几乎必然过**，
**它证明的是「没有随机性」，不是「锚选得对」**。
真正能证伪的是**换 seed 重抽锚 spot 再比**——那需要**另行签字**，我**没有**擅自加。

### 18.9 ✅ 门 **SC0–SC4** 重写（**2026-09-29 用户签字**）

> §4 的 SC0–SC4 是给 **infercnv** 写的（SC1 查 `HMM`/`rjags`、SC2 查「恶性判定一致率」、
> SC4 的「未定义」档是 infercnv 的档）。**换引擎后逐条改写如下，已生效。**
> ✅ **本表自 2026-09-29 起替代 §4 的 SC0–SC4**；§4 原版**留档不再执行**（新引擎下跑不了）。

| # | 守卫 | 判据（**新**） | 越界后 |
| :--- | :--- | :--- | :--- |
| **SC0** | 底座核对 | ①基因序匹配率 ≥99% 且重算哈希；②`Gene Expression` 行 == 18,085 且**抗体行已剔**（🔴 **2026-09-29 更正：抗体行 ∈ {0,35}，非恒 35**，见 §2.1 更正框；逐张上报）；③spot 数 == `spot_mask` 的 `n_pass`；④🔴 **fastCNV 自己的基因账逐次记账**（工具会丢 chrY/chrM，§15.8 第 1 项 ⇒ 必须报「进窗口的基因数」与「丢了哪些」） | ①②③ 任一不等 → **硬停**；④**只报不停** |
| **SC1** | 参数已冻结**且没静默走默认聚合** | §15.4 的参数**逐位相同**：`prepareCounts=FALSE`（🔴 **必须显式**）、`aggregFactor=999`、`windowSize=150`、`windowStep=10`、`topNGenes=7000`、`thresholdPercentile=0.01`、`getCNVPerChromosomeArm=TRUE`；**日志里必须出现「未聚合、逐 spot」的证据**（`prepareCounts` 若走了默认，<60,000 spot 会被并成 meta spot，**逐 spot 直接被抹掉**） | 对不上或静默聚合 → **硬停** |
| **SC2** | 🔴 **锚可复算**（**本臂第一道硬门**，**未变**） | 同一参考、同一输入，**重复 N≥3 次**，逐 spot `cnv_fraction` **≥95% 逐位相同**；且**每次的锚 spot 名单逐字节相同**。⚠️ fastCNV 是确定性的且 5.75 min/患者 ⇒ **这条现在跑得动**（infercnv 下跑不动） | 不一致 → **硬停，本臂到此为止**，如实上报「锚不可复算」 |
| **SC3** | 阴性对照 | ①锚内 spot 自己的 `cnv_fraction` 中位须 ≤ **0.05**（§18.5(a) 主阈值）；②锚内**留出**一部分 spot 不进参考，其恶性率须与进入参考的部分**无显著差**。🔴 **循环性声明仍生效**（§15.3）：锚的窗口本就是按**自己的**分位带归零的 ⇒ **「锚自己平」不是证据**，①只是**自洽检查**，**不得**写成「方法验证通过」 | ①不过 → 锚定义错 → **硬停** |
| **SC4** | 逐切片/逐患者上报，**不设通过率阈值** | 每患者报：上皮 spot 数 / 锚 spot 数 / **`cnv_fraction` 分位数（不只一个比例）** / 🔴 **敏感性档位 `0.02/0.05/0.10/0.15` 下各自的恶性 spot 比例（逐档全报）** / 各染色体臂均值；**并报「参考与观测是否同一患者」**（§14.3 守卫）。🔴 **"未定义"档可能为空** —— fastCNV 的 `cnv_fraction` 对每个进管线的 spot 都有值，**若为空就如实报空**，**不得**为了凑齐档位而造一个 | **不硬停**；**不许**事后挑患者（法则 3.2）；**不许**按阈值筛 spot |

⚠️ 三条**新引擎下不再适用**、随 §4 原版一并作废的判据：
1. SC1 的「日志中必须出现 rjags 实际被调用的证据」（infercnv 专属）；
2. SC2 的「逐 spot **恶性判定**一致率 ≥95%」（新引擎无「判定」，改为 `cnv_fraction` 逐位相同）；
3. SC4 的「`infercnv` 判不了的"未定义"档」（改为「可能为空」，见上）。

✅ **本节 2026-09-29 已签**（用户：「签字」）。本臂在新引擎下**可以开跑**；
执行顺序照 §13.3 第 2 项：**SC0 → SC1 → SC2，且 SC2 第一炮必须是单患者**。


---

### 18.10 🟡 外部正常肺锚体检**结果**（2026-09-29 跑完；§17.5 的执行落地）

脚本 `16_run_fastcnv_anchor_flatness.R`（**第 4 次跑成功**，9.5 min / 峰值 24.23 GB）；
产物 `results/08_spatial_deconv/spatial_cnv/fastcnv_anchor_flatness/`（含图与两份 `*.rds`）。
⚠️ 该次跑的**日志**里正文数字与下面一致；下方的数另行由**离线重算**（从落盘的逐 spot 分数
按切片名**确定性重建**分组）复核过一遍，**两边逐位相同**。

**运行 A（参考 = 我们 9 张自带锚 AAH 上皮，17,963 spot）**

| 切片 | n | `cnv_fraction` 中位 | [q25, q75] | 最大 |
|---|---|---|---|---|
| 9 张参考（合计） | 17,963 | 0.0000–0.0324（逐张，见日志） | — | ≤0.4907 |
| **P4_LUAD**（阳性对照） | 10,627 | **0.3843** | [0.0093, 0.6204] | 0.8657 |
| P4_Normal | 8,587 | 0.0046 | [0.0000, 0.0093] | 0.2222 |
| P4_AAH | 7,988 | 0.0046 | [0.0000, 0.0093] | 0.1944 |
| P4_AAH-1 | 7,131 | 0.0000 | [0.0000, 0.0093] | 0.0972 |
| **N1**（外部） | 3,822 | **0.0093** | [0.0000, 0.0278] | 0.3750 |
| **N3**（外部） | 1,049 | **0.1019** | [0.0648, 0.2407] | 0.8843 |

- 🟢 **F1 阳性对照 PASS**：`median(P4_LUAD)=0.3843 ≥ 0.10`；`AUC=0.7909 ≥ 0.75`。
  （⚠️ 该 AUC 与「由构造 ≈0 的参考组」比 ⇒ **偏循环**，承重的是 median；此声明 §17.5 原有，不变。）
- 🟢 **F2 同队列良性 PASS**：0.0046 / 0.0046 / 0.0000，各 ≤ 0.05。
- 🔴 **F3 外部 FAIL**：N1=0.0093（过）但 **N3=0.1019 > 0.05**。
- 🔴 **F4 批次解耦 FAIL，且是「两个方向都不过」**：
  参考=N1 时留出 N3 中位 **0.1256**；参考=N3 时留出 N1 中位 **0.1949**。

**怎么读（这一条是本次体检最重要的结论）**：
🔴 **F4 双方向不过 ⇒ 外部两张之间的偏高是「谁当参考、另一张就显高」的对称效应**，
**不是 N3 自己单张的毛病**。⇒ **外部切片 N1/N3 都不得当主锚**（照 §17.5 签发时的口径）。
⇒ 之前「N1 过了 F3」这一条**只能读成**「N1 相对于**我们自己的**参考是平的」，
**不能**读成「N1 是一张可互换的通用正常肺锚」。⚠️ **不得**写成「外部锚找到了」。
🔴 与另一条独立证据**互相印证**：N3 正是先前查出的**极浅切片**（668 counts/spot，
我们队列 3,285–5,511）⇒ **「浅 + 与 N1 不可互换」两条独立测量指向同一张片子**。
⚠️ **本体检不产生恶性判定、不进 SC0–SC4**；它只回答「外部锚能不能用」，**答案是不能当主锚**。
⚠️ **未做**：换 seed 重抽参考 spot 的稳定性复核（需另行签字）；本体检**只跑了一次**。
✅ **2026-09-29 补做完毕** ⇒ 见 **§18.11**（结论：三个 seed 下 F1/F2/F3 **逐 seed 一致**，最大极差 0.0028，
seed=1 与本节落盘结果**逐位相同**；⇒ 本节结论**不因换 seed 而翻**）。


---

### 18.11 🟡 种子敏感性复核（**2026-09-29 用户签字**；§18.10 那个「未做」的执行落地）

> §18.7 第 2 条已声明 `CNVCalling` 在给定参考下**确定性** ⇒ SC2 的重复跑**几乎必然过**，
> 它证的是「没有随机性」。真正能证伪的是 **换 seed 重抽参考 spot**。用户 2026-09-29 签：

| 项 | 已签口径 |
| :--- | :--- |
| **范围** | **只做 16_**（外部锚体检）。⚠️ 17_/SC 那套的锚（23,706 spot，**未抽稀、无 seed**）**不在本检查内**；若将来要做，须先立「锚下采样」口径 |
| **判据 A** | **F1 / F2 / F3 三条判据的结论（过 / 不过）逐 seed 一致** |
| **判据 B** | **逐切片 `cnv_fraction` 中位在 3 个 seed 间的极差 ≤ 0.01** |
| **seed** | `1 / 2 / 3`。🔴 **`seed=1` 就是 §18.10 那一次**（同一条 RNG 流、同一张序）⇒ 顺带当**复现锚点 R0** |

**R0（复现锚点，运行前定）**：本检查 `seed=1` 的**逐切片中位**必须与 §18.10 落盘的
`fastcnv_anchor_flatness/runA_spot_scores.rds` **逐位相同**（≤1e-09）⇒ 证明本检查与 16_
走的是**同一条数据通路**。**R0 不过 ⇒ 本检查整体作废**，不得报 A/B 结论。

**抽法（必须与 16_ 逐字相同，否则比不了）**：`set.seed(seed)` **一次**，然后**按 `REF_SLIDES`
顺序**逐张 `sort(epi)[sort(sample.int(length(epi), 2000))]` —— **一条 RNG 流逐张推进**；
上皮数 ≤2,000 的切片（P25 = 1,963）**不抽**，逐 seed 固定不变。

**🔴 结构性不做**：**F4（N1↔N3 批次解耦）不含任何抽样**（两张外部切片总是全量上皮）
⇒ 对 seed **免疫**，本检查**不重跑**它。登记为「未测，非『测过且稳』」。

**运行前登记的两条（2026-09-29）**：
1. 🔴 **16_ 的抽样记录不可离线审计**：`ref_sampling` 只存了 `n_epi_total / n_used / cap`，
   **没存抽中的 barcode**；而落盘的 `va$slide` 只存**切片名**（`unname(cell_slide)` 的**值**是
   切片名，`切片_barcode` 只在**名字**上）⇒ 想「把 seed=1 用过的 spot 反查出来」**做不到**。
   我一开始正是这么试的（预检脚本报「抽法不一致」，实为**我的反查错**，不是抽法不同）。
   ⇒ **R0 是唯一可行的等价性检查**（端到端比中位）。本检查把 `picks` 落盘，**补上这个口子**。
2. ⚠️ §18.10 的 F2/F3 数值离阈值**很远**（0.0000–0.0093 vs 上限 0.05；N3 = 0.1019 vs 0.05）
   ⇒ 判据 A 通过更接近「**没翻**」而不是「**压线稳住**」；读数时不得夸大。

脚本 `18_run_fastcnv_seed_sensitivity.R`；产物 `results/08_spatial_deconv/spatial_cnv/fastcnv_seed_sensitivity/`。

**结果（2026-09-29 跑完）**：**总判 过**（A 过 ／ B 过 ／ R0 过）。15.7 min，峰值 31.68 GB。
三个 seed 各落盘一份逐 spot 分数（`seed{1,2,3}_spot_scores.rds`，**含抽中的 barcode 名单**）。
⚠️ 首次起跑**崩过一次**（见下方缺陷登记 ①②），那次的日志留在 `run_fail1.log`。

**R0 复现锚点 —— 🟢 逐位相同**：15 张切片逐张中位，与 §18.10 落盘的 `runA_spot_scores.rds`
**最大绝对差 = 0.000e+00**（判据 ≤1e-09）⇒ 本检查与 16_ 走的是**同一条数据通路**，
下面的 A / B 才成立。（17,963 + 39,204 = 57,167 spot、`全零列 0` 也与 16_ 逐位一致。）

**判据 A —— 🟢 过（结论逐 seed 一致）**

| seed | F1（阳性对照） | F2（同队列良性） | F3（外部） |
| :--- | :--- | :--- | :--- |
| 1 | 过（中位 0.3843 / AUC 0.7909） | 过（0.0046, 0.0046, 0.0000） | 🔴 不过（0.0093, **0.1019**） |
| 2 | 过（中位 0.3871 / AUC 0.7928） | 过（0.0046, 0.0046, 0.0000） | 🔴 不过（0.0092, **0.1014**） |
| 3 | 过（中位 0.3860 / AUC 0.7927） | 过（0.0047, 0.0047, 0.0000） | 🔴 不过（0.0093, **0.1023**） |

**判据 B —— 🟢 过（逐切片中位极差 ≤0.01）**，最大极差 **0.0028**（在 P4_LUAD）：

| 切片 | s1 | s2 | s3 | 极差 |
| :--- | ---: | ---: | ---: | ---: |
| 9 张参考（P1/P2/P6/P9/P11/P22/P25） | 0.0046 | 0.0046 | 0.0047 | 0.0000 |
| 参考 P20_AAH | 0.0324 | 0.0323 | 0.0326 | 0.0003 |
| 参考 P24_AAH | 0.0139 | 0.0138 | 0.0140 | 0.0001 |
| 参考 P2_AAH / P4_AAH-1 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| P4_Normal / P4_AAH | 0.0046 | 0.0046 | 0.0047 | 0.0000 |
| **P4_LUAD**（阳性对照） | 0.3843 | 0.3871 | 0.3860 | **0.0028** |
| N1（外部） | 0.0093 | 0.0092 | 0.0093 | 0.0001 |
| **N3**（外部） | 0.1019 | 0.1014 | 0.1023 | 0.0009 |

**参考抽样确实换了人**（否则判据 B 是空转）：逐参考切片 seed1↔seed2 / seed1↔seed3 的
Jaccard 落在 **0.1315–0.3228**（P25 因 1,963 ≤ 上限**未抽** ⇒ 恒 1.0000）。

🔴 **本次新发现（运行前不知道，值得单独记）**：**窗口数随参考子样本变** ——
`nwin = 216 / 217 / 215`（seed 1/2/3）。⇒ `cnv_fraction` 的分母（该 spot 的窗口总数）
**不是固定的一把尺子**，逐 spot 值会随之整体挪动约**一个窗口**。
所以判据 B 那个 0.01 应当**按「约 2 个窗口」来读**：该量的最小刻度本来就 ≈ **0.0046（1/216）**，
观察到的 0.0000–0.0028 **小于一个刻度**；**0.01 这条线对这个量而言是粗的**，
**不得**把它读成「一个很紧的界」。（也解释了良性中位为何在 0.0046 / 0.0047 之间跳。）

**怎么读**：
- 🟢 **§18.10 的结论不因换 seed 而翻**：F3 三个 seed **都不过**，N3 中位始终 ≈0.101–0.102（离 0.05 很远），
  ⇒ 「**外部 N1/N3 都不得当主锚**」**不是**一次抽样的偶然。
- ⚠️ 只能读成「**结论对这个参考子样本不敏感**」，**不能**读成「结论对一般情形稳」。
- ⚠️ **F4 未测**（结构性无抽样），**不得**写成「F4 已测且稳」。
- ⚠️ 数值离阈值远 + 刻度粗 ⇒ 判据 A 接近「**没翻**」而不是「**压线稳住**」。

**两条缺陷登记（都是我自己的，2026-09-29）**：
1. 🔴 **顶层 `<<-` 崩过一次**：`RUN_MIN[[i]] <<- …` 写在**顶层 for 循环**里 ⇒
   报 `object 'RUN_MIN' not found`（`<<-` 对复杂赋值要从**外层 frame** 读旧值，顶层没有），
   **seed 1 的 3.7 min Run A 白烧**。16_ 里同一行在函数内所以没事。⇒ 改 `<-`，
   并把 `saveRDS` 提到**拿到分数之后立刻**（16_ 的同一条教训）。
2. 🔴 **我一开始想「离线反查 seed=1 抽过的 barcode」来预检，方法是错的**：
   `va$slide` 存的是**切片名**（`unname(cell_slide)` 的**值**是切片名），`切片_barcode` 只在**名字**上
   ⇒ 反查必然 0 命中。我据此报过一次「抽法与 16_ 不一致」，**那是错的**（见运行前登记 1）。
   （我当时还归因到「Seurat 把列名 `_` 换成 `-`」——**那条也没验证，不是真因**，一并更正。）
   ⇒ **R0 才是唯一可行的等价性检查**：端到端比中位，**结果 = 0.000e+00**。
3. 附带补口子：从本检查起，`seed{N}_spot_scores.rds` 里**存了抽中的 barcode 名单**，
   §18.10 那种「只记数量、无法离线审计抽了哪些 spot」的缺口不再有。


---

## 19. 🔏 签字记录九（2026-09-29）—— **借锚臂**：同性别供体汇池，补上前驱期断层

> **本节登记的是用户 2026-09-29 的一次裁定。** 出处见 §19.0 逐字原话。
> §19.5 的参数表里凡标 🕐 的项**仍待签**；**未签项不得启动计算**（法则：口径只为签字时的用途生效）。

### 19.0 促成本次的事

用户在本会话中的原话（逐字）：

> 「我的建议是借锚不然断层我们的研究就失去意义了，需要严谨描述」

**背景**：Claude 按 §17.3 排全队列方案时实测了覆盖面，发现「只跑自带锚 10 例」会使
病程轴**缺 MIA 整档**、AIS 只剩 2 张，并把原因查明为**筛选条件本身**（见 §19.2）。
用户据此裁定：**采用借锚臂**（§17.2 池 A），理由是**不借锚则期别断层，研究失去意义**。

⚠️ 本节**只**落地这一条裁定。§17.2 裁定一里与之并列的**池 B**（外部 GSE248082）
**不在本节生效范围**：其体检已在 §18.10 判为「两张都不能当主锚」，**不得**被本节复活。

### 19.1 本节是什么，**不是**什么

- **是**：把 §17.2 池 A（队列内同性别供体）从「已签原则、未实现」推进到**可执行的规格**，
  并把随之而来的混淆与守卫逐条落笔。
- **不是**：新引擎、新参数、新阈值。引擎仍是 §18.1 的 fastCNV v1.1.11，阈值仍是 §18.5(a) 的
  `0.05` ＋ 四档敏感性，门仍是 §18.9 的 SC0–SC4。**本节一个参数都不改。**
- **不是**：「借锚等价于自带锚」的声明 —— 两者的参考组织**种类不同**（见 §19.6 第 1 条），
  本臂把差异**显式化**，不隐藏。

### 19.2 为什么会断层（实测覆盖面，2026-09-29 逐文件名核对）

| 期别 | 全队列（56 张） | 只跑自带锚（现状，24 张） | 借锚后 | 备注 |
| :--- | ---: | ---: | ---: | :--- |
| Normal | 1 | 1 | **1** | 全队列仅 `P4_Normal` 一张，**借锚也补不了**（没有别的正常肺） |
| AAH | 11 | 11 | **11** | 借锚**一张都没多** —— 缺锚的 15 例本来就没有 AAH |
| AIS | 14 | **2** | **14** | P9 / P22 之外全在缺锚组 |
| MIA | 4 | **0** | **4** | P10 / P13 / P15 / P18，**全部**在缺锚组 |
| LUAD | 26 | 10 | **26** | |
| 合计 | 56 张 / 25 例 | 24 张 / 10 例 | **56 张 / 25 例** | |

🔴 **断层的根因（不是抽样的偶然）**：切片归属由「该患者有没有一块良性组织」二分。
有 AAH/Normal 切片的 10 例，与带 AIS/MIA 病灶的 15 例，**在这个队列里几乎不重叠**
⇒ **「要测的期别」与「能当参考的组织」在队列内反相关**。这正是 §3.4 登记过的
「患者间锚定义不一致」风险在**覆盖面**上的表现。
🔴 **借锚修好了期限断层，但修不了两件事**：①Normal 仍只有 1 张（下端仍只有一个人撑）；
②AAH 观测仍是 0 张新增（缺锚组没有 AAH 病灶）。
⇒ **不得**因为跑了 25 例就把期别轴写成「Normal→AAH→AIS→MIA→LUAD 五档均衡」。

### 19.3 供体-受体配对（**逐患者**；性别取自 GEO 系列元数据，2026-09-29 重取）

数据来源：`GSE307534_series_matrix.txt.gz` 的 `!Sample_characteristics_ch1` 行
（`Sex:` 与 `age:` / `smoking:` 三段），56/56 逐样本对齐 `Library name` 核过。

🔴 **一处更正（我们自己的错，2026-09-29）**：§17.1 **事实 6** 原写「自带锚的 10 例 = **6 女 / 4 男**」，
**实测为 5 女 / 5 男**（女 = P1 P4 P9 P11 P22；男 = P2 P6 P20 P24 P25）。
缺锚组的「7 女 / 8 男」**复核为正确**。⇒ 同性别供体**两边都够**，结论不变，但计数须更正。

**供体池（自带锚 10 例，各取其良性切片的上皮 spot）**

| 供体 | 性别 | 良性切片（上皮 spot） | 合计 |
| :--- | :--- | :--- | ---: |
| P1 / P4 / P9 / P11 / P22 | 女 | P1_AAH 4,745 ／ **P4_Normal 8,587 ＋ P4_AAH 7,988 ＋ P4_AAH-1 7,131** ／ P9_AAH 6,514 ／ P11_AAH 8,314 ／ P22_AAH 5,454 | **48,733** |
| P2 / P6 / P20 / P24 / P25 | 男 | P2_AAH 6,514 ／ P6_AAH 8,718 ／ P20_AAH 7,046 ／ P24_AAH 4,131 ／ P25_AAH 1,963 | **28,372** |

**受体（缺锚 15 例）与指派**

| 受体 | 性别 | 观测切片（上皮 spot） | 同性别供体池 |
| :--- | :--- | :--- | :--- |
| P7 | 女 | LUAD 6,758 ＋ LUAD-1 8,477 = 15,235 | P1 P4 P9 P11 P22 |
| P8 | 女 | AIS 3,017 ＋ LUAD 7,392 = 10,409 | 同上 |
| P10 | 女 | MIA 5,617 ＋ LUAD 8,636 = 14,253 | 同上 |
| P12 | 女 | AIS 10,216 ＋ LUAD 10,319 = 20,535 | 同上 |
| P16 | 女 | AIS 6,993 ＋ LUAD 5,234 = 12,227 | 同上 |
| P18 | 女 | MIA 7,904 ＋ LUAD 6,128 = 14,032 | 同上 |
| P21 | 女 | AIS 9,349 ＋ AIS-1 8,328 ＋ LUAD 8,029 = 25,706 | 同上 |
| P3 | 男 | AIS 4,373 ＋ LUAD 7,275 = 11,648 | P2 P6 P20 P24 P25 |
| P5 | 男 | AIS 6,468 ＋ LUAD 4,480 = 10,948 | 同上 |
| P13 | 男 | MIA 8,067 ＋ LUAD **1,205** = 9,272 | 同上 |
| P14 | 男 | AIS 9,692 ＋ LUAD 10,094 = 19,786 | 同上 |
| P15 | 男 | MIA 5,354 ＋ LUAD 9,356 = 14,710 | 同上 |
| P17 | 男 | AIS 7,357 ＋ LUAD 2,890 = 10,247 | 同上 |
| P19 | 男 | AIS 9,406 ＋ LUAD 10,292 = 19,698 | 同上 |
| P23 | 男 | AIS 7,296 ＋ AIS-1 8,574 ＋ LUAD 8,350 = 24,220 | 同上 |

**配对规则（执行前定死，不得事后挑）**：受体取**全部同性别供体**，**不取单个**、**不做 1:1 选择**；
供体**不因任何表达/CNV 指标被挑或弃**。参考 = 该性别供体池（**供体患者自己的受体若在池内须排除**，
本轮 15 例受体都是缺锚者、不可能在池内，此条对 10 例自带锚患者的对照跑才生效，见 §19.5 🕐3）。
🔴 **不按吸烟/年龄配对**：只按性别匹配，因为性别有**机制性**理由（chrX 剂量，§19.6 第 2 条），
而吸烟/年龄没有直接产生 CNV 信号的机制 ⇒ 拿它们配对只会缩小池子并引入择优。
二者**逐患者随报告列出**，作报告属性、**不作匹配条件**。

### 19.4 路径与参考构成（**走已验证的那条**）

- **入口 = 单对象 `CNVCalling` ＋ `CNVPerChromosomeArm`**（§15.4 参数一字不改）。
- 🔴 **不使用 `CNVCallingList`**（多对象汇池入口，§15.8 第 6 项实测硬崩）。
- 🔴 **路径可行性不是推断**：把「多张切片的良性上皮汇成一份参考、去打分别的切片」这件事，
  `16_run_fastcnv_anchor_flatness.R` **已在同一入口上跑通 4 次**（9 个供体 → 参考，
  观测 P4 四张 ＋ N1 ＋ N3）。本臂与它的**构造相同**，只换供体集合与受体切片。
  ⇒ §18.4 第 3 项「汇池崩、直接打在借锚上」这句**收窄**：崩的是 `CNVCallingList` 那条**不必要**的路。
- **参考构成**：同性别供体池的**良性上皮**（`argmax == 上皮`，§12.1），逐次报**每位供体贡献的 spot 数**
  与**深度**（见 §19.6 第 3 条）。
- **观测构成**：受体的**全部** AIS/MIA/LUAD 上皮 spot，**不抽稀**（与 §17.5 的观测口径一致）。

### 19.5 参数（逐项显式；法则 3.1）

| 项 | 取值 | 状态 |
| :--- | :--- | :--- |
| 引擎 / 阈值 / 门 | §18.1 fastCNV v1.1.11 ／ §18.5(a) `0.05` ＋ 四档 ／ §18.9 SC0–SC4 | ✅ 已签，**不改** |
| 路径 | 单对象 `CNVCalling`；**不用** `CNVCallingList` | ✅ 已签（§15.4 / §18.4 第 3 项） |
| 受体范围 | 缺锚 15 例（§19.3）；自带锚 10 例沿用 §17.3 的自家锚跑法 | ✅ 本节 |
| 供体池 | 同性别、全取、不择优（§19.3 规则） | ✅ 本节 |
| 供体封顶 | 🕐 **每供体患者 ≤ 2,000 spot**（超者按固定种子抽稀，**抽中名单落盘**） | **待签**（Claude 起草，可撤回） |
| 观测抽稀 | 不抽（全量） | ✅ 本节 |
| 「自带锚 vs 借锚」对照 | 🕐 **建议加**：10 例自带锚患者**另跑一次借锚**（同性别池、leave-self-out），观测集不变 | **待签** |
| D 对照锚（§11.2 的 D） | 🕐 跑 / 不跑；若跑，D 的 spot 取自「该患者全部切片」还是「仅良性切片」 | **待签**（§11.2 与 §12.1 措辞有出入，见下） |
| SC3 留出复核 | 🕐 每张良性参考切片留出 **20%**（固定种子）／ 判据 = 用 `0.05` 主阈值，两边比例差 **≤ 0.05** ／ **主表仍用全量参考**、留出只作复核（每患者多一次计算） | **待签**（Claude 起草，可撤回） |

**供体封顶那条的理由与代价（如实登记）**：本臂的参考是**多位供体汇池**，
若不封顶，`P4`（女性池里独占 23,706 / 48,733 = **49%**）会主导女性参考
⇒ 女性受体的参考**实际上接近 P4 一个人**。封顶使各供体等权，代价是引入**下采样**
⇒ 窗口数会随之变动（§18.11 已实测 216/217/215）⇒ **本臂须附 seed 复核**，
机制沿用 §18.11 的 `18_` 脚本。
🔴 **登记一处设计不对称**：自带锚 10 例的参考 = **该患者全部良性上皮、不封顶**（已按 §18.8 跑过 P4），
借锚 15 例的参考 = **封顶等权供体池**。两者**不是同一把尺子**，逐患者比对时须一并说明。

**D 臂那处措辞出入**：§11.2 写 D = 「非上皮主导 spot」（未限定切片），§12.1 第 2 项只给 C 写了
「良性切片中」。⇒ 两种读法都通。**建议以 §11.2 为准**（该患者全部切片），理由是 D 要回答的是
「换一类参考结论变不变」，不限切片才能给出足够的 spot 数。**待签**。

### 19.6 混淆与守卫（逐条）

| # | 混淆 | 守卫 / 处置 |
| :--- | :--- | :--- |
| 1 | **参考组织种类不同**：自带锚 9/10 例的良性是 **AAH 上皮**（唯一 Normal 是 P4），借锚池同理（男池 5/5 是 AAH，女池 4/5 是 AAH）⇒ **两臂的参考都不是组织学正常上皮** | 与 §17.5 的「参考是 AAH」警告**同一条**，逐臂写明；**不得**把 AAH 当参考写成「用正常肺上皮作参考」 |
| 2 | **chrX 剂量**：fastCNV 已硬丢 chrY（§15.8 第 1 项）⇒ 性别混淆**少一半**，但 **chrX 仍在信号里** | **同性别配对**（§18.5(b) 已签的理由）；跨性别借锚**禁止**，宁可记 NOT RUN |
| 3 | **不同个体 ⇒ 个体/批次差进基线**：供体与受体是不同的人（§3.4 已登记） | 逐患者标注「借自哪个池」；**逐次报供体与受体的深度**（§17.1 已实测本臂对深度敏感：计数减半 ⇒ `argmax` 移动 9.93%、门控翻转 8.30%）；**不作**深度配对（那会引入择优），只作报告 |
| 4 | **循环性**（§15.3 原声明） | 参考自己的 `cnv_fraction` 由构造 ≈ 0 ⇒ **「参考平」不是证据**；承重的是**受体观测组**的数；§19.5 的 SC3 留出是唯一非循环的复核 |
| 5 | **池 B 不可用** | §18.10 已判 N1/N3 都不能当主锚 ⇒ 本节**不引入**外部锚，池 A 是唯一来源 |

### 19.7 门与上报（SC0–SC4 在借锚臂上的落地）

- **SC0 / SC1**：逐患者照 §18.9 跑；SC0④ 的「fastCNV 基因账」逐次记账。
- **SC2**：**同一供体池参考**重复 3 次，逐 spot `cnv_fraction` 逐位相同、锚名单逐字节相同。
  ⚠️ 承 §18.9 的声明：该工具给定参考**确定性** ⇒ SC2 **几乎必然过**，它证的是「没有随机性」。
- **SC3**：照 §19.5 🕐 的留出规格（**签了才跑**）。①锚内中位 ≤ `0.05`。
- **SC4**：每患者报 上皮 spot 数 / 锚 spot 数 / `cnv_fraction` 分位数 / **四档 `0.02 0.05 0.10 0.15` 逐档比例** /
  各染色体臂均值 / 🔴 **新增「参考来源 = 自己 or 借自哪个池」**（§11.2「借来的锚须逐患者标注」的落地）。
  **不设通过率阈值、不按阈值筛 spot、不许事后挑患者**（法则 3.2）。

### 19.8 本节**不**声称

- **不**声称借锚与自带锚等价 —— 参考组织不同、个体不同，**已知不等价**（§19.6 第 1、3 条）；
- **不**声称借锚后 25 例就覆盖了完整病程轴 —— 见 §19.2 的两个「修不了」；
- **不**声称本臂产生恶性判定（`cnv_fraction` 是连续量，`CNVClassification` 只是方向分类器）；
- **不**声称「参考组平」= 方法可信（循环性，§19.6 第 4 条）；
- **不**声称借锚臂的结论可与原文比 —— §18.2 已作废「复现原文」这一前提；
- **不**声称 §19.5 的 🕐 项已签 —— 它们**全部待签**。
  🔴 **本条已过时（2026-09-29）**：第 2/3/4 项**已签并已启动计算**，以 §19.13 为准。

### 19.9 本节**不**改动的东西

- §11.2（C 主 ＋ D 对照）、§12.1（`argmax == 上皮`）、§18.5(a)(b)、**SC0–SC4 一字不改**；
- §17.2 裁定一（池 A / 池 B **并列**、池 B 不预设优先级）**不改** —— 本节只落地池 A，
  **不**把池 B 降级、也**不**把它复活（§18.10 的判决独立生效）；
- §17.3 裁定二（本轮只跑 10 例）**由本节部分取代**：10 例仍跑，**新增**缺锚 15 例的借锚跑；
- 铁律 2 / 铁律 5 / 铁律 6、**「恶性 × 权重」禁令**、RCTD 不得读成恶性 —— **均不改**。

### 19.10 本节登记后**仍待签**的四项（**未签不得启动计算**）

> 🔴 **标题已过时（2026-09-29）**：四项**均已签、计算已启动** ⇒ 以 §19.13 为准；
> 下表「Claude 的建议（未被用户选择）」是**当时的**登记，第 2/3/4 项**已成为被选择的**。

| # | 待签项 | Claude 的建议（**未被用户选择**） |
| :-- | :--- | :--- |
| 1 | 供体封顶：每供体患者 ≤ 2,000 spot ＋ 固定种子 | 建议采纳（否则女性池被 P4 独占 57%） |
| 2 | 「自带锚 vs 借锚」对照跑（10 例各多一次） | 建议采纳（直接回答「结论是不是锚挑出来的」） |
| 3 | D 对照锚：跑不跑；spot 取自全部切片还是仅良性切片 | 建议**跑**，且取**全部切片**（§11.2 措辞为准） |
| 4 | SC3 留出：20% ／ 差 ≤ `0.05` ／ 主表用全量参考 | 建议采纳 |

✅ **已签的部分**（本节落地即生效）：池 A 采用、同性别全取不择优、单对象路径、观测不抽稀、
SC4 增列「参考来源」、以及 §19.2–§19.4 的覆盖面与配对规则。

### 19.11 排期与成本估算（2026-09-29；**逐项标注哪些是实测、哪些是外推**）

**速率标定 —— 两个独立实测点，且先判定它随什么线性**

| 实测 | 对象总 spot | 单次 `CNVCalling` | ÷对象 spot | ÷仅观测 spot |
| :--- | ---: | ---: | ---: | ---: |
| §18.8 P4 SC2 第 1/2/3 次 | 34,333（参考 23,706 ＋ 观测 10,627） | 1.89 / 1.68 / 1.69 min | **4.9e-5** | 1.6e-4 |
| §18.11 seed 1/2/3 Run A | 57,167（参考 18,000 ＋ 观测 39,204） | 2.77 / 2.77 / 2.75 min | **4.85e-5** | 7.1e-5 |

⇒ 两处**独立**实测在「÷**对象总 spot**」上给出同一个常数（4.9 vs 4.85e-5），
而在「÷仅观测 spot」上差 2.3 倍 ⇒ **代价随对象总 spot 数线性**（基因数两处相同，均为 17,586）。
取 **4.85e-5 min/spot ≈ 2.9 ms/spot**。
🔴 **这仍是外推**：被实测验证过的最大对象是 **57,167 spot**；下面「乙」口径的最大对象 **111,154 spot**
＝ 实测上限的 **1.94 倍**。线性在两处小对象上吻合极好，但**未在大对象上验证**。

**内存标定 —— 🔴 只有一个实测点，比时间那条弱得多**

P4 对象 34,333 spot ⇒ 峰值 **17.06 GB** ⇒ **≈0.5 MB/spot**。
🔴 单点外推：乙口径最大对象 111,154 spot ⇒ 外推峰值 **≈54 GB**。
本机 256 GB，但**背景病理进程在跑** ⇒ **真正的瓶颈是内存，不是时间**。

**两种口径的账**（「甲」= 上皮口径、参考**不封顶**；「乙」= **全 spot**、连上皮限制也去掉）

| | 甲 | 乙 |
| :--- | ---: | ---: |
| 供体参考池（女 / 男） | 48,733 / 28,372 | 71,877 / 49,841 |
| 受体对象 spot 合计（15 例） | 801,033 | 1,266,176 |
| 自带锚对象 spot 合计（10 例） | 145,997 | 243,734 |
| `CNVCalling` 总 spot-次 | 4,881,147 | 7,793,284 |
| 计算 | 237 min | 378 min |
| ＋建对象（25 例 × ~2.5 min） | 62 min | 62 min |
| **合计** | **≈5.0 小时** | **≈7.3 小时** |
| 单对象峰值内存（最大的 P21） | **≈36 GB** | **≈54 GB** |

**每次跑的构成**：受体 **5 次** = SC2 三次 ＋ SC3 留出一次 ＋ D 臂一次；
自带锚 **6 次** = 再加一次「借锚对照」。⇒ 少跑 D 或对照，按比例下降。

**由本次算账得出的裁定（承 §19.0 用户的条件式指示：「如果预期在两天之内就全 spot」）**

1. 🕐→✅ **§19.5 的「供体封顶 2,000」取消，改用全量**：甲、乙**两种口径都**落在两天之内
   （5.0 / 7.3 小时）⇒ 条件成立。附带好处：参考**确定性** ⇒ §18.11 那条
   「锚下采样口径 ＋ seed 复核」**本臂不再需要**。
   🔴 **代价如实登记**：不封顶时**女性参考池 49%（23,706 / 48,733）来自 P4 一个人**
   ⇒ 女性受体的参考近半是同一个体 ⇒ **须逐次报供体构成**（§19.4 已有此条）。
   ⚠️ **本条按「不封顶」这一读法落笔**（承 §19.5 那条封顶提议的上下文）；若用户本意是
   「全 spot 口径」，则本条仍成立，但须与第 2 条并读。
2. **「全 spot」（乙）不得替换甲，只能并列** —— 理由见 §19.12。

**未实测、可能翻盘之处（如实列出，不得读成已保证）**：
- 线性外推（1.94 倍）**未验证**；若大对象超线性，实际时间会**超过** 5.0 / 7.3 小时。
- 内存外推**只有一个点**；若被 OOM 杀，退回封顶或分块再跑。
- 建对象耗时按 P4 的 2.3 min 外推到 25 例，而**每例切片数不同**（2–4 张），未逐例实测。
- 多供体对象上 `pooledReference=TRUE` 的行为**有先例（16_，9 供体）但未在 25 例规模上跑过**。
- 🔴 **推荐加一条内存守卫（建议，待签）**：每患者起跑前查可用内存，不足则**停并上报**，
  不得被 OOM 静默杀掉（背景病理进程优先）。

**实测回填（2026-09-29 晚起跑后逐例记；本表随跑随加，不改上面的外推）**

| 患者 | 臂 | 对象总 spot | `CNVCalling` 次数 | 总用时 | 峰值内存 |
| :--- | :--- | ---: | ---: | ---: | ---: |
| P13 | borrow（观测 MIA+LUAD） | 37,644 | 5 | **12.4 min** | 22.20 GB |
| P7 | borrow（观测 LUAD×2） | 63,968 | 5 | **18.5 min** | **34.09 GB** |

⇒ **两点观察，均与 §19.11 的外推方向一致但量级偏大**：
(1) 峰值内存 **34.09 GB** 已贴着 §19.11 外推的「最大 ≈36 GB」，而 P7 还不是最大的对象
⇒ **那条内存外推（只有一个点）确实偏乐观**，须盯住后续自带锚患者；
(2) 逐例 **12.4 / 18.5 min** ≫ §19.11 摊到的 12 min/例 ⇒ **25 例总时长大概率落在 7–10 小时**，
高于 §19.11 写的 ≈5.0 小时（**仍是两天之内** ⇒ 不影响 §19.13 的条件成立，但**描述要按实测**）。

### 19.12 「全 spot」为什么不能当主读数（若按字面读「乙」）

两条都是**构造性**的，不是偏好：

1. **它摆脱不了 RCTD。** 参考必须由 RCTD 定义（哪些 spot 算「良性上皮」），
   全 spot 也躲不掉这一步 ⇒「用全 spot 就不用 RCTD」**做不到**。
2. **它把细胞类型差异算进 CNV 信号。** 一个成纤维/免疫占主导的 spot，其 `cnv_fraction` 量的是
   「该 spot 表达与**良性上皮**参考差多远」，而主要的差来自**细胞类型不同**，不是拷贝数
   ⇒ 这正是 §11.2 给 D 臂登记的毛病，全 spot 等于**把它推广到全体**。
   ⇒ 该口径的数**不得**命名为「上皮 CNV」，只能作**并列读数**（例如「非上皮成分是否也随期别走」）。

### 19.13 签字落地（2026-09-29）＋ 对 §19.8 / §19.10「全部待签」的更正

**用户逐字**：「考虑用全 spot 需要多长时间，如果预期在两天之内就全 spot，其他决断我很认可，描述要这个真实」。

**条件已核实成立**：甲 ≈5.0 h、乙 ≈7.3 h（§19.11），**两种口径都在两天之内** ⇒ 条件触发。

**落地逐条**：

| §19.10 项 | 状态 | 实际落的 |
| :-- | :-- | :--- |
| 1 供体封顶 ≤2,000 | ✅ **签为「取消封顶、用全量」** | 参考 = 同性别供体的**全部**良性上皮；**不封顶**（§19.11 第 1 条＋🔴 代价：女性池 49% 来自 P4） |
| 2 自带锚 vs 借锚对照 | ✅ 签为**跑** | 自带锚 10 例主臂 = self，**各多跑一次** leave-self-out 借锚作 `borrow_ctrl` |
| 3 D 对照锚 | ✅ 签为**跑**，取**全部切片** | 参考 = 该患者**全部切片**的非上皮 spot（§11.2 措辞），观测集与主臂相同 |
| 4 SC3 留出 | ✅ 签为**采纳** | 每张参考切片留出 20%（seed=1）、判据 ①锚内中位 ≤0.05 ②留出前后观测组 ≥0.05 比例差 ≤0.05；**主表仍用全量参考** |
| （附）§19.11 内存守卫 | ✅ **签为加**（原为「建议，待签」） | 每患者起跑前查可用内存，`< 80 GB` 等 10 min 重试、最多 3 次，仍不足则**停并上报**，**不自降规格** |

🔴 **更正两处已过时的登记**：

- **§19.8 末条**（「不声称 §19.5 的 🕐 项已签 —— 它们全部待签」）**作废**：截至本条，第 2/3/4 项**已签**；
- **§19.10 的标题「仍待签的四项（未签不得启动计算）」在本条之后不再成立**：四项均已签，**已启动计算**。

**仍需注意的是 §19.10「Claude 的建议（未被用户选择）」这个括号**：那是**当时的**登记；用户本次的
「其他决断我很认可」使第 2/3/4 项**变成了被选择的**。⇒ 引用 §19.10 时须一并读本条，不得再引「未被用户选择」。

**执行记录**：`19_run_fastcnv_cohort.R`（逐患者）＋ `19_run_cohort_all.sh`（25 例串行驱动）；
P13 冒烟 11.1 min / 峰值 22.2 GB / SC 全 PASS，随后 **2026-09-29 22:55 起全队列脱离式运行**
（`setsid nohup`，驱动 PID 1390624 / PPID 1；日志 `logs/fastcnv_cohort_20260929/`）。

🔴 **冒烟首跑逮到的 bug（Claude 自己的代码，非数据问题；登记为「门起作用」的证据）**：
`build_obj()` 建对象时把 `slide` 元数据列**填成了完整 barcode**（值/名写反：
`setNames(paste(s,k,sep="_"), rep(s,n))`），于是 `table(obj$slide)` 有 37,644 个组而不是 7 个，
**SC1 首跑即 FAIL**。这与该患者的实际数字无关——打印出的逐切片数与预期**逐个相同**、
对象规模 18,082 × 37,644（= 28,372 ＋ 9,272）也对 ⇒ **是 SC1 这道门抓住了建对象的错**，
不是 SC1 本身过严。已修（barcode 与 slide 分列两个向量；SC1 改用
`table(factor(slide, levels=names(exp_n)))` 并**同时打印期望与实际**）。修后 SC1 用**同一批数字** PASS。

🔴 **第三个缺陷（2026-09-30 02:48 全队列实测逮到；正好落在「未实测」那条上）**：
15 例受体（借锚）**全部 PASS** 之后，链条在**第一个自带锚患者 P1** 上 `rc=1`、**P2 同样** ⇒
`19_run_cohort_all.sh` 的「连续 2 例失败 ⇒ 判系统性故障停下」**生效**（**只烧了 2×2 分钟**，
这正是那条规则存在的意义）。根因**不是 fastCNV**：主臂 `main_self` 的 SC1/SC2 **已全 PASS**
（窗口 218、逐位相同 1.000000），崩在**之后的「借锚对照」臂**：

```
Error: borrow_ctrl：参考 barcode 未在缓存中（GSM9226174_P4_Normal）
```

⇒ **我把读片集写成了「主臂需要的片子」而不是「所有臂需要的并集」**：自带锚患者的主臂参考 =
自家良性上皮 ⇒ 供体池的片子**根本没进缓存**，而「借锚对照」臂（§19.10 第 2 项）要读它们。
**受影响面 = 恰好是自带锚那 10 例**（借锚 15 例的主臂参考本来就是池子，所以没暴露）。
已修：`need_slides` 加上 `ctrl_slides`（仅当 `MAIN_KIND=="self"` 且要跑对照时）。
⚠️ 这条**只能在自带锚患者上暴露** ⇒ 印证了 §19.11「未实测、可能翻盘之处」里
「自带锚路径完全没测过」那句；**P13/P7 两个冒烟点都在借锚臂上，覆盖不到它**。

## 20. 🔴 深度配平审计（2026-10-01，**新口径 · 待签**）—— 借锚臂全队列**跑完**＋
##      「LUAD 更高」这一条被查出**主要由深度驱动**

### 20.1 触发与授权
全队列 25 例 **2026-09-29 23:41 → 2026-10-01 01:54** 脱离式跑完（驱动 PID 1548568 / PPID 1，
续跑；**25/25 PASS、零门失败**；守卫脚本 `20b_wait_then_report.sh` 在驱动退出后自动出上报）。
上报（`20_report_cohort.R`）出的是「LUAD 观测上皮 cf 高于 AIS/MIA」。
用户见数后指出该结论**可能由深度造成**，并授权「**配平一下试试**」⇒ 本审计。

### 20.2 本审计**新引入**的口径（🔴 未签字，**只作诊断**，不得直接顶替 §19.7 的上报）
| 项 | 取值 |
| :-- | :--- |
| 深度量 | **nUMI** 为主（cnv_fraction 的直接驱动量）；**nFeature** 次要复核，两套**并列报** |
| 主要对比 | `median(cf[LUAD]) − median(cf[AIS∪MIA])`，**逐患者配对**（同 §13.7.3 的操作化） |
| S1 | 在**每位患者自己**的观测上皮深度上切**五分位**，档内算同一对比，再跨患者取中位 |
| S2 | **共同支撑**：逐患者取两期别深度 **[5%,95%] 的交集**，只留落在其中的 spot |
| S3 | 🔴 **随机子样对照**：随机抽与 S2 **相同数量的 LUAD/前驱** spot（**不看深度**），`N_DRAW=500, seed=1`，取中位 |
| 深度来源 | `results/08_spatial_deconv/spatial_qc_per_spot.csv.gz`（639,816 spot）；按 `(slide, barcode)` 对齐，**命中 301,818/301,818 = 100%** |

**为什么必须有 S3**：S2 同时做了两件事——**配平深度**与**减少 spot 数**。只有 S3（同 spot 数、
不配平）才能把二者分开；否则「差变小了」可能只是样本量效应。

### 20.3 结果

**S0 深度缺口**（观测上皮，pooled 中位 nUMI）：AIS **4,268.5** / MIA **3,818.5** / LUAD **8,765**
⇒ LUAD ≈ **2.05–2.30×**。逐患者 LUAD/前驱 深度比 **中位 1.64**，**范围 0.80–12.94**（P5 高达 12.9×），
**14/16 例 > 1**。

**S1 深度五档（nUMI）**——差**只出现在深的两档**：

| 档 | 1(最浅) | 2 | 3 | 4 | 5(最深) |
| :-- | ---: | ---: | ---: | ---: | ---: |
| delta 中位 | 0.0000 | 0.0023 | 0.0023 | 0.0579 | 0.0914 |
| 患者 正/负 | 1/2 | 8/3 | 8/3 | 13/2 | 13/1 |

（nFeature 五档同型：0.0000 / 0.0000 / 0.0046 / 0.0579 / 0.1014）

**S2/S3 三向对比（nUMI，15 例三臂皆齐）**：

| 臂 | delta 中位 | 正/负 | 保留 spot |
| :-- | ---: | ---: | ---: |
| 全部 spot | **0.0323** | 13/1 | 100% |
| **随机子样（不看深度）** | **0.0323** | 13/1 | 77.6% |
| **深度配平（共同支撑）** | **0.0092** | **10/3** | 77.6% |

（nFeature：0.0323 / 0.0323 / 0.0138，同型）

**判读**：随机子样**逐位复现**了未配平的差（0.0323 = 0.0323，阳性患者同为 13/15）
⇒ **S2 的缩水不是样本量造成的，就是深度**。深度配平后差缩水 **71%**，阳性患者 13/15 → 10/15。
逐患者缩水中位 **71%**，其中 **P10 0.373 → −0.005、P18 0.143 → 0.009、P15/P12 → 0**（完全塌掉），
**P21 最稳（0.406 → 0.341，仅缩 16%）**。

### 20.4 🔴 必须一起说的话（不得省略）
1. **不能说「LUAD 的 CNV 信号是期别效应」**：深度配平后中位差 0.0092 ≈ **2/217 个窗口**，
   **贴着分辨率地板**（cf 只能取 1/217 的整数倍），且阳性患者掉到 10/15。
   ⇒ §19.7 上报里「LUAD 更高」这一条**降级为待定**；**不得**写成独立于深度的恶性信号。
2. **也不能说「全是深度」**：配平后**仍**有 10/15 患者为正、方向未翻转，**残余效应未被排除**，
   只是弱到现有分辨率下说不清。
3. **P17 的共同支撑只保住 12% 的 spot**（其 LUAD 深度远高于前驱）⇒ 该患者的配平值**不可用**，
   三向表里虽在、读的时候要剔除。
4. **口径未签**：S1–S3 的切法（五分位/共同支撑/随机子样 500 次）是**本次为诊断而设**，
   不是报告口径。要把它变成可引用的结论，**须用户签字**（含 `N_DRAW`、`seed`、`MIN_SPOT`）。
5. ⚠️ 本条**不推翻** §13.7.3 的 margin 梯度结论（那是**并列边缘**这条轴，结果仍单调/稳定）；
   两条轴**互不替代**——margin 干净**不等于**深度干净。

### 20.5 产物与执行
`results/08_spatial_deconv/spatial_cnv/cohort_borrow/depth_balance/`：
`S0_depth_gap.tsv`、`S1_bins_by_patient.tsv`、`S1_bins_summary_{nUMI,nFeature}.tsv`、
`S2S3_paired_by_patient.tsv`、`S2S3_summary.tsv`、`S4_patient_level_test.tsv`、
`S5_stage_median_matched.tsv`、`depth_balance.png`。
脚本 `08_spatial_deconv/21_depth_balance_report.R`（只读，2 分 16 秒跑完）。

🔴 **本脚本自己的 bug（登记）**：汇总函数 `summ()` 起初只读了 `r$pair`（未配平行），
**忘了并入 `r$cs`（共同支撑行）** ⇒ `both` 恒空、对比全 NA、画图崩在 `barplot`。
报错信息（`need finite 'ylim'`）指向画图，**与真因相隔很远**。已修（先 `rbind` 再分组）。

### 20.6 🔴 置换检验**设计作废**（登记为缺陷，2026-10-01）

**原 S4 设计**：逐 spot 打乱「LUAD / 前驱」标签（保留每患者的 spot 总数与深度分布），
对每次打乱算 `median(cf[假LUAD]) − median(cf[假前驱])`，跨患者取中位，与观测比。

**实测零分布退化**：P21 单独验证（nL=8,029 / nP=17,677），200 次置换打出
`sd = 0.0021`、**非零只占 20.5%**、全分布**只有 4 个取值**（−0.0046 / 0 / +0.0046 / +0.0092）。
跨患者取中位后更是恒为 **0**（`n_patient = 15` 的零分布 `median = lo2.5 = hi97.5 = 0`）。

**根因**：从 8 千个 spot 里随机抽子集，**样本中位数恒逼近总体中位数**，两组一减就是 0；
cf 又只能取 1/217 的整数倍，于是零分布塌成 0 上的点质量。**该检验分辨力≈0**，
它会给出 `p = 0` 这种**假阳性**——观测差再小也会「显著」。

**处置**：S4 **整块丢弃**（不是调参数，是设计不成立）。换成**患者级**检验：
重复单元是**患者**不是 spot。旧产物 `S4_permutation_*.tsv` 已删除，**不得引用**。

🔴 **教训登记**：队列中位差是「先逐患者取差、再跨患者取中位」的统计量，
它的零分布**必须**在患者这一个层级上打乱，**不能**下钻到 spot 层级——
下钻会把患者内变异灌进零分布，而患者内变异恰恰被中位数抹平了。

### 20.7 ✅ S4（重做：患者级）+ S5 结果（2026-10-01）

**S4 患者级检验**（`nUMI`；符号检验 = 双侧精确二项；自助法 = 重抽**患者** 5,000 次）：

| 臂 | 患者 | 有效(非零) | 正/负 | 中位差 | 自助 95% CI | 符号检验 p |
|---|---|---|---|---|---|---|
| 未配平 (all spots) | 16 | 15 | **14 / 1** | 0.0346 | **[0.0138, 0.1429]** | **0.00098** |
| 深度配平 (common support) | 15 | 13 | **10 / 3** | 0.0092 | **[0.0000, 0.0184]** | **0.092** |

（`nFeature` 同向：未配平 14/1、p=0.00098、CI [0.0138, 0.1429]；配平 10/3、p=0.092、CI [0.0000, 0.0190]。）

**判读**：未配平时**过**（CI 不含 0、p≈0.001）；深度配平后 **CI 下界恰好落到 0、p=0.092**
⇒ **在 0.05 水平上不显著**。残余方向仍偏正（10/13），但**现有分辨率+现有样本量下说不清**。

**S5 逐期别 pooled 中位**（只含同时有 LUAD 与 AIS/MIA 的 15 例患者）：

| 臂 | AIS | MIA | LUAD | LUAD ÷ 前驱 |
|---|---|---|---|---|
| 未配平 | 0.0138 (n=104,536) | 0.0138 (n=26,942) | **0.0791** (n=113,323) | ≈ **5.7×** |
| 深度配平 | 0.0140 (n=77,896) | 0.0184 (n=18,273) | **0.0323** (n=74,255) | ≈ **1.8×** |

**期别顺序未翻转**（配平前后都是 LUAD > MIA ≳ AIS），但**落差从 5.7 倍压到 1.8 倍**；
且配平后 **MIA 反而略升**（0.0138 → 0.0184）——两期别在浅深度档本就分不开。

### 20.8 对「配平之后 CNV 还有趋势吗」的一句话答复（2026-10-01）

**还有，但弱到判不了。** 形态上 LUAD > MIA ≳ AIS 的顺序没翻（S5），逐患者也仍偏正（10/13），
**可是**：(a) 中位差只剩 0.0092 ≈ 2 个窗口，(b) 符号检验 p=0.092、自助 CI 下界 = 0，
(c) 三档深度分档里浅的两档差本来就是 0（S1）。
⇒ **结论只能到「未配平时明显、配平后残余未建立」**；
**不得**据此写「LUAD 空间 CNV 更高」是独立于深度的生物学结论。


---

## 21. 🟡 逐点空间图（2026-10-01，**描述性产物 · 不是判据**）—— CNV 负荷 × RCTD 上皮权重

### 21.1 本节是什么，**不是**什么

**是**：把已经算完的两个**连续量**——`cnv_fraction`（CNV 负荷）与 RCTD `上皮` 权重——
按 Visium 真实空间坐标画在一张图上，让人**用眼睛看空间结构**。
**不是**：不是新的判据、不进任何门、**不产生恶性判定**。

🔴 **命名禁令（照抄执行）**：`cnv_fraction` 是**连续 CNV 负荷**，**不是**恶性度；
RCTD 权重**绝不当恶性判读**；两幅面板**并列**呈现、**不合成**任何单一「恶性分」。
图内文字与图注**不得**出现 malignancy / tumor / malignant 一类词（本节脚本的图注已经写明）。

### 21.2 口径

| 项 | 取值 |
|---|---|
| 患者 | **P21**（队里唯一「同患者有多张前驱 + 一次 LUAD」的代表；也是配平后最稳的一例） |
| 切片 | `GSM9226211_P21_AIS`、`GSM9226212_P21_AIS-1`、`GSM9226213_P21_LUAD` |
| spot 集 | **observation spot**（与 CNV 臂完全同一集合），共 25,706 |
| 坐标 | `array_row` / `array_col`（**不用 pxl**：边缘可为负，见 [[reference-visium-coordinate-conventions]]） |
| 色标 | 左右两列**共用同一色标**（cf 上界 = 合并 99.5 分位 0.67；上皮 0–1）⇒ 三张切片可横向比 |
| barcode 连接 | 逐张 100% 命中（RCTD 权重、坐标各 100%） |

### 21.3 外观读数（**只描述，不推断**）

- 两张 AIS 大体**淡黄**（低负荷）；LUAD 那张**组织内部一大片深红**（高负荷），斑块**连续成块**。
- 上皮权重在 LUAD 那片的**上半**也是高的（深蓝），与高负荷区**部分重叠**，但**不是重合**。
- 逐切片 `cor(cf, 上皮权重)`：AIS **0.163 / 0.200**、LUAD **0.276** ⇒ **弱正相关，解释力很低**。
- LUAD 上皮 ≥0.5 的 spot 占 **60.1%**，两张 AIS 是 **28.4% / 17.4%**。

### 21.4 🔴 看图时必须一起说的话

1. **这张图看着「LUAD 一大片红」，但它和 §20 是同一件事**：那块红有**很大一部分是深度**
   （LUAD 池深度中位是前驱的 ~2 倍），图里**没有**画深度面板 ⇒
   **不得**把这块红读成「肿瘤 CNV 扩增」。
2. **cor 只有 0.16–0.28** ⇒ 上皮占比高**并不**对应 CNV 负荷高，两者**不是一回事**；
   本图把它们**并排**而不是**相乘**，正是这个原因。
3. 色标上界 0.67 是**合并 99.5 分位**（人为截断）⇒ 少数 >0.67 的点会**溢出到同一档深红**。
4. **n=1 患者、n=1 LUAD 切片** ⇒ 本图是**示意**，不能当证据。

### 21.5 产物与执行
`results/08_spatial_deconv/spatial_cnv/cohort_borrow/spatial_map/`：
`P21_spatial_cnv_epi.png`、`P21_spatial_cnv_epi_summary.tsv`。
脚本 `08_spatial_deconv/22_spatial_cnv_map.R`（只读）。

🔴 **本脚本自己的 bug（登记，静默画错图）**：`hcl.colors(64, "YlOrRd")` 在 **R 4.2** 里
**方向与 RColorBrewer 相反**——索引 1 = 深红 `#7D0025`、索引 64 = 浅黄 `#FFFFC8`。
第一版直接按「索引 1 = 低」上色 ⇒ **CNV 面板整个画反**（AIS 低负荷显示成深红、LUAD 高负荷显示成浅黄），
**且不报任何错**。已加 `rev = TRUE` 并加 `stopifnot()` 断言首尾色值**硬钉住**方向。
（同批的 `Blues` 因为写了 `rev = TRUE` 恰好蒙对，所以只有一半错——这种「一半对」最容易蒙混过关。）
